package com.cattlefarm.admin.user;
import cn.dev33.satoken.stp.StpUtil;import com.baomidou.mybatisplus.core.toolkit.IdWorker;import com.cattlefarm.admin.auth.service.AuthService;import com.cattlefarm.admin.common.DataConflictException;import org.springframework.dao.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDateTime;import java.util.*;
@Service
public class UserService{
 private static final Set<String>SUPPORTED=Set.of("ADMIN","FARM_MANAGER","VET","BREEDER","WORKER");private final JdbcTemplate jdbc;private final AuthService auth;private final PasswordEncoder encoder;public UserService(JdbcTemplate jdbc,AuthService auth,PasswordEncoder encoder){this.jdbc=jdbc;this.auth=auth;this.encoder=encoder;}
 public List<UserDtos.Item>users(){long farm=auth.currentFarmId();return jdbc.query("SELECT u.* FROM sys_user u JOIN farm_user fu ON fu.user_id=u.user_id AND fu.farm_id=u.farm_id WHERE u.farm_id=? ORDER BY FIELD(u.status,'ENABLED','DISABLED'),u.real_name",(r,n)->new UserDtos.Item(s(r.getLong("user_id")),r.getString("username"),r.getString("real_name"),r.getString("phone"),r.getString("status"),roles(r.getLong("user_id"),farm),scopes(r.getLong("user_id"),farm),r.getTimestamp("last_login_at")==null?null:r.getTimestamp("last_login_at").toLocalDateTime(),r.getInt("version")),farm);}
 public List<UserDtos.Role>roles(){long farm=auth.currentFarmId();return jdbc.query("SELECT * FROM sys_role WHERE farm_id=? ORDER BY FIELD(role_code,'ADMIN','FARM_MANAGER','VET','BREEDER','WORKER') DESC,role_code",(r,n)->new UserDtos.Role(s(r.getLong("role_id")),r.getString("role_code"),r.getString("role_name"),r.getString("status"),rolePermissions(r.getLong("role_id")),r.getInt("version")),farm);}
 public List<UserDtos.PermissionGroup>permissions(){long farm=auth.currentFarmId();return jdbc.query("SELECT * FROM sys_permission WHERE status='ENABLED' ORDER BY sort_no,permission_id",(r,n)->new UserDtos.PermissionGroup(r.getString("permission_code"),r.getString("permission_name"),jdbc.queryForList("SELECT sr.role_code FROM sys_role_permission rp JOIN sys_role sr ON sr.role_id=rp.role_id WHERE rp.permission_id=? AND sr.farm_id=? AND sr.status='ENABLED' ORDER BY sr.role_code",String.class,r.getLong("permission_id"),farm)));}

 @Transactional public UserDtos.Role createRole(UserDtos.CreateRole r,String key){long farm=auth.currentFarmId(),operator=user();String path="/api/v1/roles";Long old=replay(farm,operator,key,path);if(old!=null)return findRole(old);if(SUPPORTED.contains(r.roleCode()))throw new DataConflictException("标准角色不可重复创建");validatePermissions(r.permissionCodes());long id=IdWorker.getId();idem(farm,operator,key,path,id);try{jdbc.update("INSERT INTO sys_role(role_id,farm_id,role_code,role_name,status) VALUES(?,?,?,?,'ENABLED')",id,farm,r.roleCode(),r.roleName().trim());}catch(DuplicateKeyException e){throw new DataConflictException("角色编码已存在");}assignPermissions(id,r.permissionCodes());auditRole(farm,operator,"ROLE_CREATED",id,"创建自定义角色");return findRole(id);}
 @Transactional public UserDtos.Role updateRole(long id,UserDtos.UpdateRole r,String key){long farm=auth.currentFarmId(),operator=user();String path="/api/v1/roles/"+id;Long old=replay(farm,operator,key,path);if(old!=null)return findRole(old);UserDtos.Role before=findRole(id);if(SUPPORTED.contains(before.roleCode()))throw new DataConflictException("标准角色权限由系统维护，不能修改");validatePermissions(r.permissionCodes());idem(farm,operator,key,path,id);int n=jdbc.update("UPDATE sys_role SET role_name=?,status=?,version=version+1 WHERE farm_id=? AND role_id=? AND version=?",r.roleName().trim(),r.status(),farm,id,r.version());if(n==0)throw new DataConflictException("角色已被其他人修改，请刷新后重试");jdbc.update("DELETE FROM sys_role_permission WHERE role_id=?",id);assignPermissions(id,r.permissionCodes());auditRole(farm,operator,"ROLE_UPDATED",id,"更新自定义角色及权限");return findRole(id);}
 @Transactional public UserDtos.Item create(UserDtos.Create r,String key){long farm=auth.currentFarmId(),operator=user();String path="/api/v1/users";Long old=replay(farm,operator,key,path);if(old!=null)return find(old);validateRoles(farm,r.roleCodes());List<UserDtos.DataScope>scopes=normalizeScopes(r.roleCodes(),r.dataScopes());validateScopes(farm,scopes);long id=IdWorker.getId(),farmUser=IdWorker.getId();idem(farm,operator,key,path,id);try{jdbc.update("INSERT INTO sys_user(user_id,farm_id,username,real_name,phone,password_hash,status) VALUES(?,?,?,?,?,?,'ENABLED')",id,farm,r.username().trim(),r.realName().trim(),r.phone(),encoder.encode(r.password()));}catch(DuplicateKeyException e){throw new DataConflictException("登录账号已存在");}jdbc.update("INSERT INTO farm_user(farm_user_id,farm_id,user_id,member_name,phone,status) VALUES(?,?,?,?,?,'ENABLED')",farmUser,farm,id,r.realName().trim(),r.phone());assign(farmUser,farm,r.roleCodes());assignScopes(farmUser,farm,scopes);audit(farm,operator,"USER_CREATED",id,"创建用户并分配角色及数据范围");return find(id);}
 @Transactional public UserDtos.Item update(long id,UserDtos.Update r,String key){long farm=auth.currentFarmId(),operator=user();String path="/api/v1/users/"+id;Long old=replay(farm,operator,key,path);if(old!=null)return find(old);UserDtos.Item before=find(id);validateRoles(farm,r.roleCodes());List<UserDtos.DataScope>scopes=normalizeScopes(r.roleCodes(),r.dataScopes());validateScopes(farm,scopes);if(id==operator&&"DISABLED".equals(r.status()))throw new DataConflictException("不能停用当前登录账号");if(before.roles().contains("ADMIN")&&!r.roleCodes().contains("ADMIN")&&adminCount(farm)<=1)throw new DataConflictException("牛场必须至少保留一个启用的管理员");idem(farm,operator,key,path,id);int n;if(r.newPassword()!=null&&!r.newPassword().isBlank())n=jdbc.update("UPDATE sys_user SET real_name=?,phone=?,status=?,password_hash=?,version=version+1 WHERE user_id=? AND farm_id=? AND version=?",r.realName().trim(),r.phone(),r.status(),encoder.encode(r.newPassword()),id,farm,r.version());else n=jdbc.update("UPDATE sys_user SET real_name=?,phone=?,status=?,version=version+1 WHERE user_id=? AND farm_id=? AND version=?",r.realName().trim(),r.phone(),r.status(),id,farm,r.version());if(n==0)throw new DataConflictException("用户已被其他人修改，请刷新后重试");Long fu=jdbc.queryForObject("SELECT farm_user_id FROM farm_user WHERE farm_id=? AND user_id=?",Long.class,farm,id);jdbc.update("UPDATE farm_user SET member_name=?,phone=?,status=? WHERE farm_user_id=?",r.realName().trim(),r.phone(),r.status(),fu);jdbc.update("DELETE FROM farm_user_role WHERE farm_user_id=?",fu);assign(fu,farm,r.roleCodes());jdbc.update("DELETE FROM farm_user_data_scope WHERE farm_id=? AND farm_user_id=?",farm,fu);assignScopes(fu,farm,scopes);audit(farm,operator,"USER_UPDATED",id,"更新用户状态、角色及数据范围");return find(id);}
 private UserDtos.Item find(long id){return users().stream().filter(x->x.userId().equals(s(id))).findFirst().orElseThrow(()->new DataConflictException("用户不存在"));}
 private UserDtos.Role findRole(long id){return roles().stream().filter(x->x.roleId().equals(s(id))).findFirst().orElseThrow(()->new DataConflictException("角色不存在"));}
 private List<String>roles(long id,long farm){return jdbc.queryForList("SELECT r.role_code FROM farm_user fu JOIN farm_user_role ur ON ur.farm_user_id=fu.farm_user_id JOIN sys_role r ON r.role_id=ur.role_id WHERE fu.farm_id=? AND fu.user_id=? AND r.status='ENABLED'",String.class,farm,id);}
 private List<UserDtos.DataScope>scopes(long id,long farm){return jdbc.query("SELECT s.scope_type,s.scope_object_id FROM farm_user fu JOIN farm_user_data_scope s ON s.farm_user_id=fu.farm_user_id AND s.farm_id=fu.farm_id WHERE fu.farm_id=? AND fu.user_id=? ORDER BY s.scope_type,s.scope_object_id",(r,n)->new UserDtos.DataScope(r.getString(1),r.getObject(2)==null?null:r.getObject(2).toString()),farm,id);}
 private List<String>rolePermissions(long role){return jdbc.queryForList("SELECT p.permission_code FROM sys_role_permission rp JOIN sys_permission p ON p.permission_id=rp.permission_id WHERE rp.role_id=? AND p.status='ENABLED' ORDER BY p.sort_no",String.class,role);}
 private void validateRoles(long farm,List<String>roles){for(String role:new HashSet<>(roles)){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM sys_role WHERE farm_id=? AND role_code=? AND status='ENABLED'",Integer.class,farm,role);if(n==null||n==0)throw new DataConflictException("角色不存在或已停用："+role);}}
 private void validatePermissions(List<String>codes){for(String code:new LinkedHashSet<>(codes)){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM sys_permission WHERE permission_code=? AND status='ENABLED'",Integer.class,code);if(n==null||n==0)throw new DataConflictException("权限组不存在或已停用："+code);}}
 private void assignPermissions(long role,List<String>codes){for(String code:new LinkedHashSet<>(codes)){Long permission=jdbc.queryForObject("SELECT permission_id FROM sys_permission WHERE permission_code=? AND status='ENABLED'",Long.class,code);jdbc.update("INSERT INTO sys_role_permission(id,role_id,permission_id) VALUES(?,?,?)",IdWorker.getId(),role,permission);}}
 private void assign(long fu,long farm,List<String>codes){for(String code:new LinkedHashSet<>(codes)){Long role=jdbc.queryForObject("SELECT role_id FROM sys_role WHERE farm_id=? AND role_code=?",Long.class,farm,code);jdbc.update("INSERT INTO farm_user_role(id,farm_user_id,role_id) VALUES(?,?,?)",IdWorker.getId(),fu,role);}}
 private List<UserDtos.DataScope>normalizeScopes(List<String>roles,List<UserDtos.DataScope>scopes){if(scopes!=null&&!scopes.isEmpty())return scopes;if(roles.contains("ADMIN")||roles.contains("FARM_MANAGER"))return List.of(new UserDtos.DataScope("ALL",null));return List.of(new UserDtos.DataScope("SELF_ASSIGNED",null));}
 private void validateScopes(long farm,List<UserDtos.DataScope>scopes){Set<String>unique=new HashSet<>();for(var s:scopes){Long object=parseScopeObject(s);String key=s.scopeType()+":"+object;if(!unique.add(key))throw new DataConflictException("数据范围不能重复");if("ALL".equals(s.scopeType())&&scopes.size()>1)throw new DataConflictException("ALL 数据范围不能与其他范围同时设置");if("HERD".equals(s.scopeType())&&countScope("herd","herd_id",farm,object)==0)throw new DataConflictException("数据范围中的牛群不存在");if("BARN".equals(s.scopeType())&&countScope("barn","barn_id",farm,object)==0)throw new DataConflictException("数据范围中的栏舍不存在");}}
 private void assignScopes(long fu,long farm,List<UserDtos.DataScope>scopes){for(var s:scopes)jdbc.update("INSERT INTO farm_user_data_scope(scope_id,farm_id,farm_user_id,scope_type,scope_object_id) VALUES(?,?,?,?,?)",IdWorker.getId(),farm,fu,s.scopeType(),parseScopeObject(s));}
 private Long parseScopeObject(UserDtos.DataScope s){if(!List.of("HERD","BARN").contains(s.scopeType())){if(s.scopeObjectId()!=null&&!s.scopeObjectId().isBlank())throw new DataConflictException(s.scopeType()+" 数据范围不能指定对象");return null;}if(s.scopeObjectId()==null||s.scopeObjectId().isBlank())throw new DataConflictException(s.scopeType()+" 数据范围必须指定对象");try{return Long.valueOf(s.scopeObjectId());}catch(Exception e){throw new DataConflictException("数据范围对象编号格式错误");}}
 private int countScope(String table,String pk,long farm,Long id){if(id==null)return 0;Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM "+table+" WHERE farm_id=? AND "+pk+"=?",Integer.class,farm,id);return n==null?0:n;}
 private long adminCount(long farm){Long n=jdbc.queryForObject("SELECT COUNT(DISTINCT u.user_id) FROM sys_user u JOIN farm_user fu ON fu.user_id=u.user_id AND fu.farm_id=u.farm_id JOIN farm_user_role ur ON ur.farm_user_id=fu.farm_user_id JOIN sys_role r ON r.role_id=ur.role_id WHERE u.farm_id=? AND u.status='ENABLED' AND r.role_code='ADMIN'",Long.class,farm);return n==null?0:n;}
 private void audit(long f,long u,String a,long id,String reason){jdbc.update("INSERT INTO operation_log(operation_log_id,farm_id,user_id,module_code,action_type,business_type,business_id,reason) VALUES(?,?,?,'SYSTEM',?,'USER',?,?)",IdWorker.getId(),f,u,a,id,reason);}
 private void auditRole(long f,long u,String a,long id,String reason){jdbc.update("INSERT INTO operation_log(operation_log_id,farm_id,user_id,module_code,action_type,business_type,business_id,reason) VALUES(?,?,?,'SYSTEM',?,'ROLE',?,?)",IdWorker.getId(),f,u,a,id,reason);}
 private void idem(long f,long u,String k,String p,long id){jdbc.update("INSERT INTO idempotency_record(farm_id,user_id,idempotency_key,request_path,business_id,expires_at) VALUES(?,?,?,?,?,?)",f,u,k,p,id,LocalDateTime.now().plusDays(1));}
 private Long replay(long f,long u,String k,String p){try{return jdbc.queryForObject("SELECT business_id FROM idempotency_record WHERE farm_id=? AND user_id=? AND idempotency_key=? AND request_path=? AND expires_at>NOW()",Long.class,f,u,k,p);}catch(EmptyResultDataAccessException e){return null;}}
 private long user(){return StpUtil.getLoginIdAsLong();}private static String s(long id){return Long.toString(id);}
}
