package com.cattlefarm.admin.report;
import cn.dev33.satoken.stp.StpUtil;import com.baomidou.mybatisplus.core.toolkit.IdWorker;import com.cattlefarm.admin.auth.service.AuthService;import com.cattlefarm.admin.common.DataConflictException;import com.fasterxml.jackson.databind.ObjectMapper;import org.springframework.beans.factory.annotation.Value;import org.springframework.core.io.*;import org.springframework.dao.EmptyResultDataAccessException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.*;import java.util.*;
@Service
public class ReportExportService{
 private final JdbcTemplate jdbc;private final AuthService auth;private final ReportService reports;private final ObjectMapper json;private final Path root,node,script;
 public ReportExportService(JdbcTemplate jdbc,AuthService auth,ReportService reports,ObjectMapper json,@Value("${report.export.root:D:/Develop/cattle-system/data/exports}")String root,@Value("${report.export.node:C:/Users/14924/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/bin/node.exe}")String node,@Value("${report.export.script:D:/Develop/cattle-system/deploy/export-report.mjs}")String script){this.jdbc=jdbc;this.auth=auth;this.reports=reports;this.json=json;this.root=Path.of(root);this.node=Path.of(node);this.script=Path.of(script);}
 public List<ExportDtos.Item>list(){long farm=auth.currentFarmId();expire(farm);return jdbc.query("SELECT * FROM export_log WHERE farm_id=? ORDER BY created_at DESC",(r,n)->map(r),farm);}
 public ExportDtos.Item find(long id){long farm=auth.currentFarmId();expire(farm);try{return jdbc.queryForObject("SELECT * FROM export_log WHERE export_log_id=? AND farm_id=?",(r,n)->map(r),id,farm);}catch(EmptyResultDataAccessException e){throw new DataConflictException("导出任务不存在");}}
 @Transactional public ExportDtos.Item create(ExportDtos.Create request,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();String path="/api/v1/reports/exports";Long old=replay(farm,user,key,path);if(old!=null)return find(old);if(request.endDate().isBefore(request.startDate()))throw new DataConflictException("结束日期不能早于开始日期");long id=IdWorker.getId();idem(farm,user,key,path,id);jdbc.update("INSERT INTO export_log(export_log_id,farm_id,module,filter_condition,status,operator_id) VALUES(?,?,'OVERVIEW',?,'PROCESSING',?)",id,farm,"{\"startDate\":\""+request.startDate()+"\",\"endDate\":\""+request.endDate()+"\"}",user);try{var report=reports.overview(request.startDate(),request.endDate());Path dir=root.resolve(Long.toString(farm));Files.createDirectories(dir);String name="cattle-report-"+request.startDate()+"-"+request.endDate()+"-"+id+".xlsx";Path output=dir.resolve(name),input=dir.resolve(id+".json");Map<String,Object>payload=json.convertValue(report,Map.class);payload.put("exportedAt",LocalDateTime.now().withNano(0).toString().replace('T',' '));Files.writeString(input,json.writeValueAsString(payload),StandardCharsets.UTF_8);Process p=new ProcessBuilder(node.toString(),script.toString(),input.toString(),output.toString()).redirectErrorStream(true).start();String processOutput=new String(p.getInputStream().readAllBytes(),StandardCharsets.UTF_8);int exit=p.waitFor();Files.deleteIfExists(input);if(exit!=0||!Files.exists(output))throw new IllegalStateException(processOutput.isBlank()?"电子表格生成失败":processOutput);int rows=report.inventory().size()+report.movements().size()+report.breeding().size()+report.healthVaccination().size()+report.feeding().size()+report.tasks().size()+report.lifecycleStages().size()+report.herds().size();jdbc.update("UPDATE export_log SET status='SUCCESS',file_name=?,file_url=?,row_count=?,expired_at=?,updated_at=NOW() WHERE export_log_id=?",name,output.toString(),rows,LocalDateTime.now().plusDays(7),id);audit(farm,user,"REPORT_EXPORTED",id,"生成经营报表");}catch(Exception e){jdbc.update("UPDATE export_log SET status='FAILED',fail_reason=?,updated_at=NOW() WHERE export_log_id=?",trim(e.getMessage()),id);}return find(id);}
 public Resource download(long id){ExportDtos.Item item=find(id);if(!"SUCCESS".equals(item.status()))throw new DataConflictException("导出文件尚不可下载");long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();String path=jdbc.queryForObject("SELECT file_url FROM export_log WHERE export_log_id=? AND farm_id=?",String.class,id,farm);Path file=Path.of(path);if(!file.normalize().startsWith(root.normalize())||!Files.isRegularFile(file))throw new DataConflictException("导出文件不存在或已清理");audit(farm,user,"REPORT_DOWNLOADED",id,"下载经营报表");return new FileSystemResource(file);}
 private void expire(long farm){jdbc.update("UPDATE export_log SET status='EXPIRED',updated_at=NOW() WHERE farm_id=? AND status='SUCCESS' AND expired_at<NOW()",farm);}private ExportDtos.Item map(java.sql.ResultSet r)throws java.sql.SQLException{return new ExportDtos.Item(Long.toString(r.getLong("export_log_id")),r.getString("module"),r.getString("status"),r.getString("file_name"),(Integer)r.getObject("row_count"),r.getString("fail_reason"),r.getTimestamp("expired_at")==null?null:r.getTimestamp("expired_at").toLocalDateTime(),r.getTimestamp("created_at").toLocalDateTime());}private void audit(long f,long u,String a,long id,String reason){jdbc.update("INSERT INTO operation_log(operation_log_id,farm_id,user_id,module_code,action_type,business_type,business_id,reason) VALUES(?,?,?,'REPORT',?,'EXPORT',?,?)",IdWorker.getId(),f,u,a,id,reason);}private void idem(long f,long u,String k,String p,long id){jdbc.update("INSERT INTO idempotency_record(farm_id,user_id,idempotency_key,request_path,business_id,expires_at) VALUES(?,?,?,?,?,?)",f,u,k,p,id,LocalDateTime.now().plusDays(1));}private Long replay(long f,long u,String k,String p){try{return jdbc.queryForObject("SELECT business_id FROM idempotency_record WHERE farm_id=? AND user_id=? AND idempotency_key=? AND request_path=? AND expires_at>NOW()",Long.class,f,u,k,p);}catch(EmptyResultDataAccessException e){return null;}}private String trim(String s){if(s==null)return"未知错误";return s.length()>500?s.substring(0,500):s;}
}
