package com.cattlefarm.admin.growth;
import cn.dev33.satoken.stp.StpUtil;import com.baomidou.mybatisplus.core.toolkit.IdWorker;import com.cattlefarm.admin.auth.service.AuthService;import com.cattlefarm.admin.common.DataConflictException;import com.cattlefarm.admin.scope.DataScopeService;
import org.springframework.dao.EmptyResultDataAccessException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.util.StringUtils;
import java.math.*;import java.time.*;import java.time.temporal.ChronoUnit;import java.util.*;
@Service
public class GrowthService{
 private final JdbcTemplate jdbc;private final AuthService auth;private final DataScopeService scope;public GrowthService(JdbcTemplate jdbc,AuthService auth,DataScopeService scope){this.jdbc=jdbc;this.auth=auth;this.scope=scope;}
 public List<GrowthDtos.WeightItem>weights(String cattleId){long farm=auth.currentFarmId();Long cid=StringUtils.hasText(cattleId)?parse(cattleId,"牛只"):null;if(cid!=null&&!scope.unrestricted())scope.assertCattle(cid);List<RawWeight>raw=jdbc.query("""
  SELECT w.weight_id,w.cattle_id,c.ear_tag_no,c.name,w.measure_date,w.weight_kg,w.measure_method,w.version FROM weight_record w JOIN cattle c ON c.cattle_id=w.cattle_id AND c.farm_id=w.farm_id WHERE w.farm_id=? AND w.is_void=0 AND (? IS NULL OR w.cattle_id=?) ORDER BY w.cattle_id,w.measure_date
  """,(rs,row)->new RawWeight(rs.getLong(1),rs.getLong(2),rs.getString(3),rs.getString(4),rs.getTimestamp(5).toLocalDateTime(),rs.getBigDecimal(6),rs.getString(7),rs.getInt(8)),farm,cid,cid);List<GrowthDtos.WeightItem>out=new ArrayList<>();Map<Long,RawWeight>previous=new HashMap<>();for(RawWeight r:raw){RawWeight p=previous.put(r.cattleId(),r);BigDecimal change=p==null?null:r.weight().subtract(p.weight());BigDecimal adg=null;if(p!=null){long days=Math.max(1,ChronoUnit.DAYS.between(p.date().toLocalDate(),r.date().toLocalDate()));adg=change.divide(BigDecimal.valueOf(days),2,RoundingMode.HALF_UP);}String warning=warning(r.weight(),p,change,adg);out.add(new GrowthDtos.WeightItem(Long.toString(r.id()),Long.toString(r.cattleId()),r.earTag(),r.name(),r.date(),r.weight(),r.method(),change,adg,warning!=null,warning,r.version()));}Collections.reverse(out);return out.stream().filter(x->scope.unrestricted()||scope.canAccessCattle(Long.parseLong(x.cattleId()))).toList();}
 public List<GrowthDtos.BodyConditionItem>bodyConditions(String cattleId){long farm=auth.currentFarmId();Long cid=StringUtils.hasText(cattleId)?parse(cattleId,"牛只"):null;if(cid!=null&&!scope.unrestricted())scope.assertCattle(cid);return jdbc.query("""
  SELECT b.body_condition_id,b.cattle_id,c.ear_tag_no,c.name,b.score_date,b.score,b.remark,b.version FROM body_condition_record b JOIN cattle c ON c.cattle_id=b.cattle_id AND c.farm_id=b.farm_id WHERE b.farm_id=? AND b.is_void=0 AND (? IS NULL OR b.cattle_id=?) ORDER BY b.score_date DESC
  """,(rs,row)->new GrowthDtos.BodyConditionItem(Long.toString(rs.getLong(1)),Long.toString(rs.getLong(2)),rs.getString(3),rs.getString(4),rs.getTimestamp(5).toLocalDateTime(),rs.getBigDecimal(6),rs.getString(7),rs.getInt(8)),farm,cid,cid).stream().filter(x->scope.unrestricted()||scope.canAccessCattle(Long.parseLong(x.cattleId()))).toList();}
 @Transactional public GrowthDtos.WeightItem recordWeight(GrowthDtos.CreateWeight r,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();Long replay=replay(farm,user,key,"/api/v1/growth/weights");if(replay!=null)return findWeight(replay);long cattle=parse(r.cattleId(),"牛只");validateCattle(farm,cattle);long id=IdWorker.getId();idem(farm,user,key,"/api/v1/growth/weights",id);jdbc.update("INSERT INTO weight_record(weight_id,farm_id,cattle_id,measure_date,weight_kg,measure_method,recorder_id,remark) VALUES (?,?,?,?,?,?,?,?)",id,farm,cattle,r.measureDate(),r.weightKg(),r.measureMethod(),user,r.remark());event(farm,cattle,"WEIGHT_RECORDED",r.measureDate(),"weight_record",id,"称重："+r.weightKg().stripTrailingZeros().toPlainString()+" kg",user);audit(farm,user,"WEIGHT_RECORDED","WEIGHT",id);return findWeight(id);}
 @Transactional public GrowthDtos.BodyConditionItem recordBodyCondition(GrowthDtos.CreateBodyCondition r,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();Long replay=replay(farm,user,key,"/api/v1/growth/body-conditions");if(replay!=null)return findCondition(replay);long cattle=parse(r.cattleId(),"牛只");validateCattle(farm,cattle);long id=IdWorker.getId();idem(farm,user,key,"/api/v1/growth/body-conditions",id);jdbc.update("INSERT INTO body_condition_record(body_condition_id,farm_id,cattle_id,score_date,score,recorder_id,remark) VALUES (?,?,?,?,?,?,?)",id,farm,cattle,r.scoreDate(),r.score(),user,r.remark());event(farm,cattle,"BODY_CONDITION_RECORDED",r.scoreDate(),"body_condition_record",id,"体况评分："+r.score().stripTrailingZeros().toPlainString(),user);audit(farm,user,"BODY_CONDITION_RECORDED","BODY_CONDITION",id);return findCondition(id);}
 public GrowthDtos.Trend trend(String cattleId){long id=parse(cattleId,"牛只");long farm=auth.currentFarmId();String ear;try{ear=jdbc.queryForObject("SELECT ear_tag_no FROM cattle WHERE cattle_id=? AND farm_id=?",String.class,id,farm);}catch(EmptyResultDataAccessException e){throw new DataConflictException("牛只不存在");}List<GrowthDtos.WeightItem>w=weights(cattleId);Collections.reverse(w);List<GrowthDtos.BodyConditionItem>b=bodyConditions(cattleId);Collections.reverse(b);return new GrowthDtos.Trend(cattleId,ear,w,b);}
 public GrowthDtos.HerdTrend herdTrend(String herdId){long herd=parse(herdId,"herd"),farm=auth.currentFarmId();String name;try{name=jdbc.queryForObject("SELECT herd_name FROM herd WHERE farm_id=? AND herd_id=?",String.class,farm,herd);}catch(EmptyResultDataAccessException e){throw new DataConflictException("牛群不存在");}List<Long> visible=scope.accessibleCattleIds();if(visible.isEmpty())return new GrowthDtos.HerdTrend(herdId,name,List.of());String marks=String.join(",",Collections.nCopies(visible.size(),"?"));List<Object> args=new ArrayList<>();args.add(farm);args.add(herd);args.addAll(visible);List<GrowthDtos.HerdWeightPoint> points=jdbc.query("SELECT DATE(w.measure_date) d,ROUND(AVG(w.weight_kg),2) avg_weight,COUNT(DISTINCT w.cattle_id) cattle_count FROM weight_record w JOIN cattle c ON c.cattle_id=w.cattle_id AND c.farm_id=w.farm_id WHERE w.farm_id=? AND c.herd_id=? AND w.is_void=0 AND w.cattle_id IN ("+marks+") GROUP BY DATE(w.measure_date) ORDER BY DATE(w.measure_date)",(rs,row)->new GrowthDtos.HerdWeightPoint(rs.getDate(1).toLocalDate().atStartOfDay(),rs.getBigDecimal(2),rs.getLong(3)),args.toArray());return new GrowthDtos.HerdTrend(herdId,name,points);}
 private GrowthDtos.WeightItem findWeight(long id){return weights(null).stream().filter(x->x.weightId().equals(Long.toString(id))).findFirst().orElseThrow();}private GrowthDtos.BodyConditionItem findCondition(long id){return bodyConditions(null).stream().filter(x->x.bodyConditionId().equals(Long.toString(id))).findFirst().orElseThrow();}
 private String warning(BigDecimal current,RawWeight p,BigDecimal change,BigDecimal adg){if(p==null){if(current.compareTo(BigDecimal.valueOf(50))<0)return"首次体重低于50kg，请确认测量或牛只阶段";if(current.compareTo(BigDecimal.valueOf(1500))>0)return"首次体重高于1500kg，请确认测量";return null;}if(change.signum()<0)return"体重较上次下降";if(adg.compareTo(BigDecimal.valueOf(3))>0)return"平均日增重超过3kg，请确认测量间隔和数据";BigDecimal ratio=change.abs().divide(p.weight(),4,RoundingMode.HALF_UP);if(ratio.compareTo(BigDecimal.valueOf(.3))>0)return"相邻体重变化超过30%，请确认测量";return null;}
 private void validateCattle(long farm,long id){if(!scope.unrestricted())scope.assertCattle(id);Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM cattle WHERE farm_id=? AND cattle_id=? AND presence_status='IN_FIELD'",Integer.class,farm,id);if(n==null||n==0)throw new DataConflictException("牛只不存在或已离场");}
 private void event(long farm,long cattle,String type,LocalDateTime date,String table,long id,String summary,long user){jdbc.update("INSERT INTO cattle_event(event_id,farm_id,cattle_id,event_type,event_date,business_table,business_id,summary,operator_id,is_void) VALUES (?,?,?,?,?,?,?,?,?,0)",IdWorker.getId(),farm,cattle,type,date,table,id,summary,user);}private void audit(long farm,long user,String action,String type,long id){jdbc.update("INSERT INTO operation_log(operation_log_id,farm_id,user_id,module_code,action_type,business_type,business_id,reason) VALUES (?,?,?,?,?,?,?,'登记生长数据')",IdWorker.getId(),farm,user,"GROWTH",action,type,id);}
 private void idem(long farm,long user,String key,String path,long id){jdbc.update("INSERT INTO idempotency_record(farm_id,user_id,idempotency_key,request_path,business_id,expires_at) VALUES (?,?,?,?,?,?)",farm,user,key,path,id,LocalDateTime.now().plusDays(1));}private Long replay(long farm,long user,String key,String path){try{return jdbc.queryForObject("SELECT business_id FROM idempotency_record WHERE farm_id=? AND user_id=? AND idempotency_key=? AND request_path=? AND expires_at>NOW()",Long.class,farm,user,key,path);}catch(EmptyResultDataAccessException e){return null;}}private long parse(String v,String label){try{return Long.parseLong(v);}catch(NumberFormatException e){throw new DataConflictException(label+"编号格式错误");}}
 private record RawWeight(long id,long cattleId,String earTag,String name,LocalDateTime date,BigDecimal weight,String method,int version){}
}
