package com.cattlefarm.admin.cattleimport;

import cn.dev33.satoken.stp.StpUtil;
import com.baomidou.mybatisplus.core.toolkit.IdWorker;
import com.cattlefarm.admin.auth.service.AuthService;
import com.cattlefarm.admin.common.DataConflictException;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import java.io.*;
import java.nio.file.*;
import java.time.*;
import java.time.format.DateTimeParseException;
import java.util.*;

@Service
public class CattleImportService {
    private static final List<String> HEADERS = List.of("耳标号*","名称","性别*","出生日期","来源类型*","入场日期*","生命周期阶段*","栏舍编码","牛群编码","备注");
    private static final Set<String> SEX = Set.of("MALE","FEMALE"), SOURCE = Set.of("BIRTH","PURCHASE"), STAGE = Set.of("CALF","GROWING","RESERVE","COW","BULL");
    private final JdbcTemplate jdbc; private final AuthService auth; private final Path root; private final DataFormatter formatter = new DataFormatter();

    public CattleImportService(JdbcTemplate jdbc,AuthService auth,@Value("${import.storage.root:D:/Develop/cattle-system/data/imports}")String root){this.jdbc=jdbc;this.auth=auth;this.root=Path.of(root).toAbsolutePath().normalize();}

    public ByteArrayResource template(){try(var workbook=new XSSFWorkbook();var out=new ByteArrayOutputStream()){Sheet sheet=workbook.createSheet("牛只导入");Row header=sheet.createRow(0);CellStyle style=workbook.createCellStyle();Font font=workbook.createFont();font.setBold(true);style.setFont(font);for(int i=0;i<HEADERS.size();i++){Cell c=header.createCell(i);c.setCellValue(HEADERS.get(i));c.setCellStyle(style);sheet.setColumnWidth(i,i==9?8000:4500);}Row example=sheet.createRow(1);String[] values={"示例-001","示例牛","FEMALE","2025-01-01","PURCHASE","2026-01-01","GROWING","B001","H001","示例行，导入前请删除"};for(int i=0;i<values.length;i++)example.createCell(i).setCellValue(values[i]);workbook.write(out);return new ByteArrayResource(out.toByteArray());}catch(IOException e){throw new IllegalStateException("模板生成失败",e);}}

    @Transactional
    public ImportDtos.Result validate(MultipartFile file,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();String path="/api/v1/cattle/import/validate";Long old=replay(farm,user,key,path);if(old!=null)return result(old);if(file==null||file.isEmpty())throw new DataConflictException("导入文件不能为空");String name=safeName(file.getOriginalFilename());if(!name.toLowerCase(Locale.ROOT).endsWith(".xlsx"))throw new DataConflictException("仅支持 .xlsx 导入文件");if(file.getSize()>10L*1024*1024)throw new DataConflictException("导入文件不能超过 10 MB");long id=IdWorker.getId();Path dir=root.resolve(Long.toString(farm)).normalize(),target=dir.resolve(id+".xlsx").normalize();try{Files.createDirectories(dir);file.transferTo(target);Validation validation=parseAndValidate(target,farm);idem(farm,user,key,path,id);String status=validation.errors().isEmpty()?"VALIDATED":"INVALID";int failed=failedRows(validation.errors());jdbc.update("INSERT INTO import_log(import_log_id,farm_id,module,file_name,total_count,success_count,fail_count,error_summary,status,source_file_url,operator_id) VALUES(?,?,'CATTLE',?,?,?,?,?,?,?,?)",id,farm,name,validation.rows().size()+failed,0,failed,summary(validation.errors()),status,target.toString(),user);writeErrors(farm,id,validation.errors());audit(farm,user,"CATTLE_IMPORT_VALIDATED",id,"牛只导入预校验："+status);return result(id);}catch(IOException|RuntimeException e){try{Files.deleteIfExists(target);}catch(IOException ignored){}if(e instanceof RuntimeException runtime)throw runtime;throw new DataConflictException("导入文件保存失败");}}

    @Transactional
    public ImportDtos.Result confirm(ImportDtos.Confirm request,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong(),id=parseId(request.importId());String path="/api/v1/cattle/import/confirm";Long old=replay(farm,user,key,path);if(old!=null)return result(old);Map<String,Object> log=logRow(farm,id);if(!"CATTLE".equals(log.get("module")))throw new DataConflictException("导入批次模块不匹配");if("CONFIRMED".equals(log.get("status")))throw new DataConflictException("导入批次已确认");if(!"VALIDATED".equals(log.get("status")))throw new DataConflictException("只有预校验通过的批次可以确认");Path source=Path.of(String.valueOf(log.get("source_file_url"))).toAbsolutePath().normalize();if(!source.startsWith(root)||!Files.isRegularFile(source))throw new DataConflictException("导入源文件不存在或已清理");Validation validation=parseAndValidate(source,farm);if(!validation.errors().isEmpty()){jdbc.update("DELETE FROM import_error_detail WHERE farm_id=? AND import_log_id=?",farm,id);writeErrors(farm,id,validation.errors());jdbc.update("UPDATE import_log SET status='INVALID',fail_count=?,error_summary=? WHERE farm_id=? AND import_log_id=?",failedRows(validation.errors()),summary(validation.errors()),farm,id);throw new DataConflictException("数据在预校验后发生变化，请查看错误明细并重新上传");}idem(farm,user,key,path,id);int success=0;for(CattleRow r:validation.rows()){long cattle=IdWorker.getId();jdbc.update("INSERT INTO cattle(cattle_id,farm_id,ear_tag_no,name,sex,birth_date,source_type,entry_date,lifecycle_stage,presence_status,health_status,herd_id,barn_id,remark,created_by,updated_by,version) VALUES(?,?,?,?,?,?,?,?,?,'IN_FIELD','NORMAL',?,?,?,?,?,0)",cattle,farm,r.earTag(),empty(r.name()),r.sex(),r.birthDate(),r.source(),r.entryDate(),r.stage(),r.herdId(),r.barnId(),empty(r.remark()),user,user);jdbc.update("INSERT INTO cattle_event(event_id,farm_id,cattle_id,event_type,event_date,business_table,business_id,summary,operator_id,is_void) VALUES(?,?,?,'CATTLE_CREATED',?,'cattle',?,'批量导入创建牛只档案',?,0)",IdWorker.getId(),farm,cattle,r.entryDate().atStartOfDay(),cattle,user);success++;}jdbc.update("UPDATE import_log SET status='CONFIRMED',success_count=?,fail_count=0,error_summary=NULL WHERE farm_id=? AND import_log_id=?",success,farm,id);audit(farm,user,"CATTLE_IMPORT_CONFIRMED",id,"确认导入 "+success+" 头牛只");return result(id);}

    public List<ImportDtos.LogItem>list(){long farm=auth.currentFarmId();return jdbc.query("SELECT * FROM import_log WHERE farm_id=? ORDER BY created_at DESC",(r,n)->new ImportDtos.LogItem(Long.toString(r.getLong("import_log_id")),r.getString("module"),r.getString("file_name"),r.getString("status"),r.getInt("total_count"),r.getInt("success_count"),r.getInt("fail_count"),r.getString("error_summary"),Long.toString(r.getLong("operator_id")),r.getTimestamp("created_at").toLocalDateTime()),farm);}
    public List<ImportDtos.ErrorItem>errors(long id){long farm=auth.currentFarmId();logRow(farm,id);return jdbc.query("SELECT * FROM import_error_detail WHERE farm_id=? AND import_log_id=? ORDER BY row_no,error_id",(r,n)->new ImportDtos.ErrorItem(Long.toString(r.getLong("error_id")),r.getInt("row_no"),r.getString("field_name"),r.getString("raw_value"),r.getString("error_code"),r.getString("error_message")),farm,id);}
    private ImportDtos.Result result(long id){Map<String,Object>r=logRow(auth.currentFarmId(),id);return new ImportDtos.Result(Long.toString(id),String.valueOf(r.get("status")),((Number)r.get("total_count")).intValue(),((Number)r.get("success_count")).intValue(),((Number)r.get("fail_count")).intValue(),errors(id));}

    private Validation parseAndValidate(Path file,long farm){List<CattleRow> rows=new ArrayList<>();List<ImportError> errors=new ArrayList<>();Set<String> tags=new HashSet<>();try(InputStream input=Files.newInputStream(file);Workbook workbook=WorkbookFactory.create(input)){Sheet sheet=workbook.getSheetAt(0);Row header=sheet.getRow(0);for(int i=0;i<HEADERS.size();i++)if(header==null||!HEADERS.get(i).equals(formatter.formatCellValue(header.getCell(i)).trim()))throw new DataConflictException("导入模板表头不匹配，请重新下载模板");for(int index=1;index<=sheet.getLastRowNum();index++){Row row=sheet.getRow(index);if(row==null||blankRow(row))continue;int no=index+1;String ear=text(row,0),name=text(row,1),sex=text(row,2).toUpperCase(Locale.ROOT),birth=text(row,3),source=text(row,4).toUpperCase(Locale.ROOT),entry=text(row,5),stage=text(row,6).toUpperCase(Locale.ROOT),barnCode=text(row,7),herdCode=text(row,8),remark=text(row,9);boolean invalid=false;if(ear.isBlank()){errors.add(err(no,"earTagNo",ear,"REQUIRED","耳标号不能为空"));invalid=true;}else if(!tags.add(ear)){errors.add(err(no,"earTagNo",ear,"DUPLICATE_FILE","文件内耳标号重复"));invalid=true;}else if(count("SELECT COUNT(*) FROM cattle WHERE farm_id=? AND ear_tag_no=?",farm,ear)>0){errors.add(err(no,"earTagNo",ear,"DUPLICATE_DATABASE","耳标号已存在"));invalid=true;}if(!SEX.contains(sex)){errors.add(err(no,"sex",sex,"INVALID_ENUM","性别必须为 MALE 或 FEMALE"));invalid=true;}if(!SOURCE.contains(source)){errors.add(err(no,"sourceType",source,"INVALID_ENUM","来源类型必须为 BIRTH 或 PURCHASE"));invalid=true;}if(!STAGE.contains(stage)){errors.add(err(no,"lifecycleStage",stage,"INVALID_ENUM","生命周期阶段不合法"));invalid=true;}LocalDate birthDate=date(birth,no,"birthDate",false,errors),entryDate=date(entry,no,"entryDate",true,errors);if(entryDate==null)invalid=true;if(!birth.isBlank()&&birthDate==null)invalid=true;if(birthDate!=null&&entryDate!=null&&birthDate.isAfter(entryDate)){errors.add(err(no,"birthDate",birth,"DATE_ORDER","出生日期不能晚于入场日期"));invalid=true;}Long barn=lookup("barn","barn_id","barn_code",farm,barnCode);if(!barnCode.isBlank()&&barn==null){errors.add(err(no,"barnCode",barnCode,"NOT_FOUND","栏舍编码不存在"));invalid=true;}Long herd=lookup("herd","herd_id","herd_code",farm,herdCode);if(!herdCode.isBlank()&&herd==null){errors.add(err(no,"herdCode",herdCode,"NOT_FOUND","牛群编码不存在"));invalid=true;}if(herd!=null&&barn!=null&&count("SELECT COUNT(*) FROM herd WHERE farm_id=? AND herd_id=? AND barn_id=?",farm,herd,barn)==0){errors.add(err(no,"herdCode",herdCode,"LOCATION_MISMATCH","牛群不属于所填栏舍"));invalid=true;}if(!invalid)rows.add(new CattleRow(no,ear,name,sex,birthDate,source,entryDate,stage,barn,herd,remark));}}catch(DataConflictException e){throw e;}catch(Exception e){throw new DataConflictException("无法解析 Excel 文件，请确认文件未损坏");}return new Validation(rows,errors);}
    private boolean blankRow(Row r){for(int i=0;i<HEADERS.size();i++)if(!text(r,i).isBlank())return false;return true;}private String text(Row r,int i){return formatter.formatCellValue(r.getCell(i)).trim();}private LocalDate date(String v,int row,String field,boolean required,List<ImportError> errors){if(v.isBlank()){if(required)errors.add(err(row,field,v,"REQUIRED","日期不能为空"));return null;}try{return LocalDate.parse(v);}catch(DateTimeParseException e){errors.add(err(row,field,v,"INVALID_DATE","日期格式必须为 yyyy-MM-dd"));return null;}}private Long lookup(String table,String pk,String code,long farm,String value){if(value.isBlank())return null;try{return jdbc.queryForObject("SELECT "+pk+" FROM "+table+" WHERE farm_id=? AND "+code+"=?",Long.class,farm,value);}catch(EmptyResultDataAccessException e){return null;}}private long count(String sql,Object...a){Number n=jdbc.queryForObject(sql,Number.class,a);return n==null?0:n.longValue();}
    private void writeErrors(long farm,long id,List<ImportError> errors){for(ImportError e:errors)jdbc.update("INSERT INTO import_error_detail(error_id,farm_id,import_log_id,row_no,field_name,raw_value,error_code,error_message) VALUES(?,?,?,?,?,?,?,?)",IdWorker.getId(),farm,id,e.row(),e.field(),trim(e.raw(),500),e.code(),e.message());}private int failedRows(List<ImportError> errors){return (int)errors.stream().map(ImportError::row).distinct().count();}private String summary(List<ImportError> e){return e.isEmpty()?null:"发现 "+failedRows(e)+" 个失败行、"+e.size()+" 个校验错误";}private ImportError err(int row,String field,String raw,String code,String message){return new ImportError(row,field,raw,code,message);}private String safeName(String v){String n=v==null?"cattle-import.xlsx":Paths.get(v).getFileName().toString();return n.length()>255?n.substring(n.length()-255):n;}private String empty(String v){return v==null||v.isBlank()?null:v;}private String trim(String v,int max){return v==null?null:v.length()>max?v.substring(0,max):v;}
    private Map<String,Object>logRow(long farm,long id){try{return jdbc.queryForMap("SELECT * FROM import_log WHERE farm_id=? AND import_log_id=?",farm,id);}catch(EmptyResultDataAccessException e){throw new DataConflictException("导入批次不存在");}}private long parseId(String v){try{return Long.parseLong(v);}catch(Exception e){throw new DataConflictException("导入批次编号格式错误");}}private void audit(long f,long u,String a,long id,String reason){jdbc.update("INSERT INTO operation_log(operation_log_id,farm_id,user_id,module_code,action_type,business_type,business_id,reason) VALUES(?,?,?,'IMPORT',?,'IMPORT',?,?)",IdWorker.getId(),f,u,a,id,reason);}private void idem(long f,long u,String k,String p,long id){jdbc.update("INSERT INTO idempotency_record(farm_id,user_id,idempotency_key,request_path,business_id,expires_at) VALUES(?,?,?,?,?,?)",f,u,k,p,id,LocalDateTime.now().plusDays(1));}private Long replay(long f,long u,String k,String p){try{return jdbc.queryForObject("SELECT business_id FROM idempotency_record WHERE farm_id=? AND user_id=? AND idempotency_key=? AND request_path=? AND expires_at>NOW()",Long.class,f,u,k,p);}catch(EmptyResultDataAccessException e){return null;}}
    private record CattleRow(int row,String earTag,String name,String sex,LocalDate birthDate,String source,LocalDate entryDate,String stage,Long barnId,Long herdId,String remark){}private record ImportError(int row,String field,String raw,String code,String message){}private record Validation(List<CattleRow>rows,List<ImportError>errors){}
}
