<script setup lang="ts">
import{onMounted,ref,watch}from'vue';import{ElMessage}from'element-plus';import{Refresh}from'@element-plus/icons-vue';import{getExportLogs,getLogins,getOperations,type ExportLog,type Login,type Operation}from'../api/audit';import{getStoredUser}from'../auth/session'
const isAdmin=getStoredUser()?.roles.includes('ADMIN')??false,tab=ref('operations'),loading=ref(false),page=ref(1),pageSize=20,total=ref(0),module=ref(''),status=ref(''),dates=ref<[string,string]|null>(null),operations=ref<Operation[]>([]),logins=ref<Login[]>([]),exports=ref<ExportLog[]>([])
const moduleLabels:Record<string,string>={CATTLE:'牛只档案',TRANSFER:'转群',HEALTH:'健康',VACCINATION:'防疫',GROWTH:'生长',BREEDING:'繁育',TASK:'任务',FEEDING:'配料',REPORT:'报表'}
async function load(){loading.value=true;try{const base={page:page.value,pageSize};if(tab.value==='operations'){const r=await getOperations({...base,module:module.value||undefined,startDate:dates.value?.[0],endDate:dates.value?.[1]});operations.value=r.items;total.value=r.total}else if(tab.value==='logins'){const r=await getLogins({...base,result:status.value||undefined});logins.value=r.items;total.value=r.total}else{const r=await getExportLogs({...base,status:status.value||undefined});exports.value=r.items;total.value=r.total}}catch(e:any){ElMessage.error(e.response?.data?.message||'审计日志加载失败')}finally{loading.value=false}}watch(tab,()=>{page.value=1;status.value='';load()});onMounted(load)
</script>
<template><div><div class="page-heading"><div><p class="eyebrow">安全与追溯</p><h1>审计中心</h1></div><el-button :icon="Refresh" :loading="loading" @click="load">刷新</el-button></div><el-tabs v-model="tab"><el-tab-pane label="操作日志" name="operations"/><el-tab-pane v-if="isAdmin" label="登录日志" name="logins"/><el-tab-pane label="导出日志" name="exports"/></el-tabs><section class="filter-bar audit-filter"><el-select v-if="tab==='operations'" v-model="module" clearable placeholder="业务模块" @change="load"><el-option v-for="(label,value) in moduleLabels" :key="value" :label="label" :value="value"/></el-select><el-select v-else v-model="status" clearable placeholder="状态" @change="load"><el-option v-if="tab==='logins'" label="成功" value="SUCCESS"/><el-option v-if="tab==='logins'" label="失败" value="FAILED"/><template v-else><el-option v-for="x in ['PENDING','PROCESSING','SUCCESS','FAILED','EXPIRED']" :key="x" :label="x" :value="x"/></template></el-select><el-date-picker v-if="tab==='operations'" v-model="dates" type="daterange" value-format="YYYY-MM-DD" range-separator="至" @change="load"/></section>
<section class="table-panel"><el-table v-if="tab==='operations'" v-loading="loading" :data="operations"><el-table-column prop="createdAt" label="时间" width="180"/><el-table-column prop="operatorName" label="操作人" width="110"/><el-table-column label="模块" width="100"><template #default="s">{{moduleLabels[s.row.moduleCode]||s.row.moduleCode}}</template></el-table-column><el-table-column prop="actionType" label="动作" min-width="180"/><el-table-column label="业务对象" min-width="190"><template #default="s">{{s.row.businessType}} · {{s.row.businessId}}</template></el-table-column><el-table-column prop="reason" label="原因/说明" min-width="220" show-overflow-tooltip/></el-table>
<el-table v-else-if="tab==='logins'" v-loading="loading" :data="logins"><el-table-column prop="createdAt" label="时间" width="180"/><el-table-column prop="account" label="账号"/><el-table-column prop="operatorName" label="人员"/><el-table-column label="结果"><template #default="s"><el-tag :type="s.row.result==='SUCCESS'?'success':'danger'">{{s.row.result}}</el-tag></template></el-table-column><el-table-column prop="clientIp" label="客户端 IP"/><el-table-column prop="failureReason" label="失败原因"/></el-table>
<el-table v-else v-loading="loading" :data="exports"><el-table-column prop="createdAt" label="时间" width="180"/><el-table-column prop="operatorName" label="导出人" width="110"/><el-table-column prop="fileName" label="文件" min-width="290"/><el-table-column prop="rowCount" label="数据行" width="90"/><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="s.row.status==='SUCCESS'?'success':s.row.status==='FAILED'?'danger':'info'">{{s.row.status}}</el-tag></template></el-table-column><el-table-column prop="expiredAt" label="过期时间" width="180"/><el-table-column prop="failReason" label="失败原因"/></el-table><div class="pager"><el-pagination v-model:current-page="page" :page-size="pageSize" :total="total" layout="total, prev, pager, next" @current-change="load"/></div></section></div></template>
<style scoped>.audit-filter{grid-template-columns:minmax(180px,240px) minmax(280px,360px)}.pager{display:flex;justify-content:flex-end;padding:16px}.el-select,.el-date-editor{width:100%}@media(max-width:700px){.audit-filter{grid-template-columns:1fr}}</style>
