package com.cattlefarm.admin.audit;
import com.cattlefarm.admin.auth.service.AuthService;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.util.StringUtils;import java.time.LocalDate;import java.util.*;
@Service
public class AuditService{
 private final JdbcTemplate jdbc;private final AuthService auth;public AuditService(JdbcTemplate jdbc,AuthService auth){this.jdbc=jdbc;this.auth=auth;}
 public AuditDtos.Page<AuditDtos.Operation>operations(int page,int size,String module,LocalDate start,LocalDate end){long farm=auth.currentFarmId();int offset=(page-1)*size;String m=StringUtils.hasText(module)?module:null;Long total=jdbc.queryForObject("SELECT COUNT(*) FROM operation_log WHERE farm_id=? AND (? IS NULL OR module_code=?) AND (? IS NULL OR created_at>=?) AND (? IS NULL OR created_at<?)",Long.class,farm,m,m,start,start,end,end==null?null:end.plusDays(1));var items=jdbc.query("SELECT l.*,u.real_name FROM operation_log l LEFT JOIN sys_user u ON u.user_id=l.user_id WHERE l.farm_id=? AND (? IS NULL OR l.module_code=?) AND (? IS NULL OR l.created_at>=?) AND (? IS NULL OR l.created_at<?) ORDER BY l.created_at DESC LIMIT ? OFFSET ?",(r,n)->new AuditDtos.Operation(s(r.getLong("operation_log_id")),r.getString("real_name"),r.getString("module_code"),r.getString("action_type"),r.getString("business_type"),s(r.getLong("business_id")),r.getString("reason"),r.getTimestamp("created_at").toLocalDateTime()),farm,m,m,start,start,end,end==null?null:end.plusDays(1),size,offset);return new AuditDtos.Page<>(total==null?0:total,page,size,items);}
 public AuditDtos.Page<AuditDtos.Login>logins(int page,int size,String result){long farm=auth.currentFarmId();int offset=(page-1)*size;String status=StringUtils.hasText(result)?result:null;Long total=jdbc.queryForObject("SELECT COUNT(*) FROM login_log l JOIN sys_user u ON u.user_id=l.user_id WHERE u.farm_id=? AND (? IS NULL OR l.login_result=?)",Long.class,farm,status,status);var items=jdbc.query("SELECT l.*,u.real_name FROM login_log l JOIN sys_user u ON u.user_id=l.user_id WHERE u.farm_id=? AND (? IS NULL OR l.login_result=?) ORDER BY l.created_at DESC LIMIT ? OFFSET ?",(r,n)->new AuditDtos.Login(s(r.getLong("login_log_id")),r.getString("login_account"),r.getString("real_name"),r.getString("login_result"),r.getString("failure_reason"),r.getString("client_ip"),r.getTimestamp("created_at").toLocalDateTime()),farm,status,status,size,offset);return new AuditDtos.Page<>(total==null?0:total,page,size,items);}
 public AuditDtos.Page<AuditDtos.Export>exports(int page,int size,String status){long farm=auth.currentFarmId();int offset=(page-1)*size;String st=StringUtils.hasText(status)?status:null;Long total=jdbc.queryForObject("SELECT COUNT(*) FROM export_log WHERE farm_id=? AND (? IS NULL OR status=?)",Long.class,farm,st,st);var items=jdbc.query("SELECT e.*,u.real_name FROM export_log e LEFT JOIN sys_user u ON u.user_id=e.operator_id WHERE e.farm_id=? AND (? IS NULL OR e.status=?) ORDER BY e.created_at DESC LIMIT ? OFFSET ?",(r,n)->new AuditDtos.Export(s(r.getLong("export_log_id")),r.getString("real_name"),r.getString("module"),r.getString("filter_condition"),r.getString("status"),r.getString("file_name"),(Integer)r.getObject("row_count"),r.getString("fail_reason"),r.getTimestamp("expired_at")==null?null:r.getTimestamp("expired_at").toLocalDateTime(),r.getTimestamp("created_at").toLocalDateTime()),farm,st,st,size,offset);return new AuditDtos.Page<>(total==null?0:total,page,size,items);}
 private static String s(long id){return Long.toString(id);}
}
