package com.cattlefarm.admin.vaccination;
import cn.dev33.satoken.stp.StpUtil;import com.baomidou.mybatisplus.core.toolkit.IdWorker;import com.cattlefarm.admin.auth.service.AuthService;import com.cattlefarm.admin.common.DataConflictException;import com.cattlefarm.admin.scope.DataScopeService;
import org.springframework.dao.EmptyResultDataAccessException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.util.StringUtils;
import java.time.*;import java.util.*;import com.cattlefarm.admin.task.TaskService;

@Service
public class VaccinationService {
 private final JdbcTemplate jdbc;private final AuthService auth;private final TaskService tasks;private final DataScopeService scope;public VaccinationService(JdbcTemplate jdbc,AuthService auth,TaskService tasks,DataScopeService scope){this.jdbc=jdbc;this.auth=auth;this.tasks=tasks;this.scope=scope;}
 public List<VaccinationDtos.PlanItem> plans(String status){long farm=auth.currentFarmId();jdbc.update("UPDATE vaccination_plan SET status='OVERDUE',version=version+1 WHERE farm_id=? AND status IN('NOT_STARTED','IN_PROGRESS') AND due_date<CURDATE()",farm);String f=StringUtils.hasText(status)?status:null;
  return jdbc.query("""
   SELECT p.*,(SELECT GROUP_CONCAT(CONCAT(t.target_type,':',t.target_object_id) ORDER BY t.target_type SEPARATOR ',') FROM vaccination_plan_target t WHERE t.farm_id=p.farm_id AND t.plan_id=p.plan_id) target_summary,
   (SELECT COUNT(DISTINCT c.cattle_id) FROM cattle c WHERE c.farm_id=p.farm_id AND c.presence_status='IN_FIELD' AND EXISTS(SELECT 1 FROM vaccination_plan_target t WHERE t.plan_id=p.plan_id AND ((t.target_type='CATTLE' AND t.target_object_id=c.cattle_id) OR (t.target_type='BARN' AND t.target_object_id=c.barn_id) OR (t.target_type='HERD' AND t.target_object_id=c.herd_id)))) target_count,
   (SELECT COUNT(DISTINCT ec.cattle_id) FROM vaccination_execution e JOIN vaccination_execution_cattle ec ON ec.execution_id=e.execution_id AND ec.farm_id=e.farm_id WHERE e.farm_id=p.farm_id AND e.plan_id=p.plan_id AND e.is_void=0) executed_count
   FROM vaccination_plan p WHERE p.farm_id=? AND (? IS NULL OR p.status=?) ORDER BY p.plan_date DESC,p.created_at DESC
   """,(rs,row)->new VaccinationDtos.PlanItem(Long.toString(rs.getLong("plan_id")),rs.getString("plan_name"),rs.getString("vaccine_item"),rs.getDate("plan_date").toLocalDate(),rs.getDate("due_date").toLocalDate(),rs.getString("status"),rs.getString("target_summary"),rs.getLong("target_count"),rs.getLong("executed_count"),rs.getString("remark"),rs.getInt("version")),farm,f,f);}
 public List<VaccinationDtos.ExecutionItem> executions(String planId){long farm=auth.currentFarmId();Long pid=StringUtils.hasText(planId)?parse(planId,"vaccination plan"):null;return jdbc.query("""
  SELECT e.execution_id,e.plan_id,p.plan_name,e.execution_date,e.vaccine_item,e.batch_no,u.real_name,e.remark,e.version,
  COUNT(ec.id) cattle_count,GROUP_CONCAT(c.ear_tag_no ORDER BY c.ear_tag_no SEPARATOR ', ') cattle_summary
  FROM vaccination_execution e LEFT JOIN vaccination_plan p ON p.plan_id=e.plan_id AND p.farm_id=e.farm_id
  LEFT JOIN sys_user u ON u.user_id=e.executor_id AND u.farm_id=e.farm_id
  JOIN vaccination_execution_cattle ec ON ec.execution_id=e.execution_id AND ec.farm_id=e.farm_id
  JOIN cattle c ON c.cattle_id=ec.cattle_id AND c.farm_id=e.farm_id
  WHERE e.farm_id=? AND e.is_void=0 AND (? IS NULL OR e.plan_id=?)
  GROUP BY e.execution_id,e.plan_id,p.plan_name,e.execution_date,e.vaccine_item,e.batch_no,u.real_name,e.remark,e.version
  ORDER BY e.execution_date DESC,e.created_at DESC
  """,(rs,row)->new VaccinationDtos.ExecutionItem(Long.toString(rs.getLong(1)),rs.getObject(2)==null?null:rs.getObject(2).toString(),rs.getString(3),rs.getTimestamp(4).toLocalDateTime(),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getLong(10),rs.getString(11),rs.getInt(9)),farm,pid,pid);}
 @Transactional public VaccinationDtos.PlanItem createPlan(VaccinationDtos.CreatePlan r,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();Long replay=replay(farm,user,key,"/api/v1/vaccinations/plans");if(replay!=null)return findPlan(replay);
  if(r.dueDate().isBefore(r.planDate()))throw new DataConflictException("截止日期不能早于计划日期");for(var t:r.targets())validateTarget(farm,t);long id=IdWorker.getId();idem(farm,user,key,"/api/v1/vaccinations/plans",id);
  jdbc.update("INSERT INTO vaccination_plan(plan_id,farm_id,plan_name,vaccine_item,plan_date,due_date,responsible_user_id,status,remark,created_by,updated_by) VALUES (?,?,?,?,?,?,?,'NOT_STARTED',?,?,?)",id,farm,r.planName().trim(),r.vaccineItem().trim(),r.planDate(),r.dueDate(),user,r.remark(),user,user);
  for(var t:r.targets())jdbc.update("INSERT INTO vaccination_plan_target(target_id,farm_id,plan_id,target_type,target_object_id) VALUES (?,?,?,?,?)",IdWorker.getId(),farm,id,t.targetType(),parse(t.targetObjectId(),"防疫目标"));var primary=r.targets().get(0);long objectId=parse(primary.targetObjectId(),"防疫目标");tasks.createAutomatic(farm,id,"VACCINATION_PLAN","VACCINATION_EXECUTION",r.planName().trim(),"CATTLE".equals(primary.targetType())?objectId:null,"HERD".equals(primary.targetType())?objectId:null,"BARN".equals(primary.targetType())?objectId:null,r.planDate(),r.dueDate(),user,"IMPORTANT");
  audit(farm,user,"VACCINATION_PLAN_CREATED","VACCINATION_PLAN",id,"创建防疫计划");return findPlan(id);}
 @Transactional public VaccinationDtos.ExecutionResult execute(VaccinationDtos.CreateExecution r,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();Long replay=replay(farm,user,key,"/api/v1/vaccinations/executions");if(replay!=null)return executionResult(replay);
  Long planId=StringUtils.hasText(r.planId())?parse(r.planId(),"防疫计划"):null;PlanState plan=planId==null?null:planState(farm,planId);if(plan!=null){if("CANCELLED".equals(plan.status())||"DONE".equals(plan.status()))throw new DataConflictException("该计划已完成或取消");if(!plan.item().equals(r.vaccineItem().trim()))throw new DataConflictException("执行项目与防疫计划不一致");}
  Set<Long> ids=new HashSet<>();for(var item:r.cattle()){long cattle=parse(item.cattleId(),"牛只");if(!ids.add(cattle))throw new DataConflictException("执行牛只不可重复");validateCattle(farm,planId,cattle);}
  long id=IdWorker.getId();idem(farm,user,key,"/api/v1/vaccinations/executions",id);jdbc.update("INSERT INTO vaccination_execution(execution_id,farm_id,plan_id,execution_date,vaccine_item,batch_no,executor_id,remark) VALUES (?,?,?,?,?,?,?,?)",id,farm,planId,r.executionDate(),r.vaccineItem().trim(),r.batchNo(),user,r.remark());
  for(var item:r.cattle()){long cattle=parse(item.cattleId(),"牛只");jdbc.update("INSERT INTO vaccination_execution_cattle(id,farm_id,execution_id,cattle_id,reaction) VALUES (?,?,?,?,?)",IdWorker.getId(),farm,id,cattle,item.reaction());event(farm,cattle,r.executionDate(),id,"完成防疫："+r.vaccineItem().trim(),user);}
  if(planId!=null){long target=targetCount(farm,planId),done=executedCount(farm,planId);String state=done>=target&&target>0?"DONE":"IN_PROGRESS";jdbc.update("UPDATE vaccination_plan SET status=?,updated_by=?,version=version+1 WHERE plan_id=? AND farm_id=?",state,user,planId,farm);tasks.finishSource(farm,"VACCINATION_PLAN",planId,"VACCINATION_EXECUTION",done+"/"+target+" 头已执行",user,state);}
  audit(farm,user,"VACCINATION_EXECUTED","VACCINATION_EXECUTION",id,"登记防疫执行");return executionResult(id);}
 private VaccinationDtos.PlanItem findPlan(long id){return plans(null).stream().filter(p->p.planId().equals(Long.toString(id))).findFirst().orElseThrow(()->new DataConflictException("防疫计划不存在"));}
 private VaccinationDtos.ExecutionResult executionResult(long id){long farm=auth.currentFarmId();return jdbc.queryForObject("SELECT e.execution_id,e.plan_id,COUNT(ec.id) cattle_count,COALESCE(p.status,'STANDALONE') plan_status FROM vaccination_execution e LEFT JOIN vaccination_execution_cattle ec ON ec.execution_id=e.execution_id LEFT JOIN vaccination_plan p ON p.plan_id=e.plan_id WHERE e.execution_id=? AND e.farm_id=? GROUP BY e.execution_id,e.plan_id,p.status",(rs,row)->new VaccinationDtos.ExecutionResult(Long.toString(rs.getLong(1)),rs.getObject(2)==null?null:rs.getObject(2).toString(),rs.getInt(3),rs.getString(4)),id,farm);}
 private void validateTarget(long farm,VaccinationDtos.Target t){long id=parse(t.targetObjectId(),"防疫目标");String table=switch(t.targetType()){case "BARN"->"barn";case "HERD"->"herd";default->"cattle";};String pk=switch(t.targetType()){case "BARN"->"barn_id";case "HERD"->"herd_id";default->"cattle_id";};Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM "+table+" WHERE farm_id=? AND "+pk+"=?",Integer.class,farm,id);if(n==null||n==0)throw new DataConflictException("防疫目标不存在或不属于当前牛场");}
 private void validateCattle(long farm,Long plan,long cattle){if(!scope.unrestricted())scope.assertCattle(cattle);Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM cattle c WHERE c.farm_id=? AND c.cattle_id=? AND c.presence_status='IN_FIELD'"+(plan==null?"":" AND EXISTS(SELECT 1 FROM vaccination_plan_target t WHERE t.plan_id="+plan+" AND ((t.target_type='CATTLE' AND t.target_object_id=c.cattle_id) OR(t.target_type='BARN' AND t.target_object_id=c.barn_id) OR(t.target_type='HERD' AND t.target_object_id=c.herd_id)))"),Integer.class,farm,cattle);if(n==null||n==0)throw new DataConflictException("牛只不在场或不属于计划范围");}
 private PlanState planState(long farm,long id){try{return jdbc.queryForObject("SELECT vaccine_item,status FROM vaccination_plan WHERE farm_id=? AND plan_id=?",(rs,row)->new PlanState(rs.getString(1),rs.getString(2)),farm,id);}catch(EmptyResultDataAccessException e){throw new DataConflictException("防疫计划不存在");}}
 private long targetCount(long farm,long plan){Long n=jdbc.queryForObject("SELECT COUNT(DISTINCT c.cattle_id) FROM cattle c WHERE c.farm_id=? AND c.presence_status='IN_FIELD' AND EXISTS(SELECT 1 FROM vaccination_plan_target t WHERE t.plan_id=? AND ((t.target_type='CATTLE' AND t.target_object_id=c.cattle_id) OR(t.target_type='BARN' AND t.target_object_id=c.barn_id) OR(t.target_type='HERD' AND t.target_object_id=c.herd_id)))",Long.class,farm,plan);return n==null?0:n;}
 private long executedCount(long farm,long plan){Long n=jdbc.queryForObject("SELECT COUNT(DISTINCT ec.cattle_id) FROM vaccination_execution e JOIN vaccination_execution_cattle ec ON ec.execution_id=e.execution_id WHERE e.plan_id=? AND e.is_void=0",Long.class,plan);return n==null?0:n;}
 private void event(long farm,long cattle,LocalDateTime date,long id,String summary,long user){jdbc.update("INSERT INTO cattle_event(event_id,farm_id,cattle_id,event_type,event_date,business_table,business_id,summary,operator_id,is_void) VALUES (?,?,?,'VACCINATION_EXECUTED',?,'vaccination_execution',?,?,?,0)",IdWorker.getId(),farm,cattle,date,id,summary,user);}
 private void audit(long farm,long user,String action,String type,long id,String reason){jdbc.update("INSERT INTO operation_log(operation_log_id,farm_id,user_id,module_code,action_type,business_type,business_id,reason) VALUES (?,?,?,?,?,?,?,?)",IdWorker.getId(),farm,user,"VACCINATION",action,type,id,reason);}
 private void idem(long farm,long user,String key,String path,long id){jdbc.update("INSERT INTO idempotency_record(farm_id,user_id,idempotency_key,request_path,business_id,expires_at) VALUES (?,?,?,?,?,?)",farm,user,key,path,id,LocalDateTime.now().plusDays(1));}
 private Long replay(long farm,long user,String key,String path){try{return jdbc.queryForObject("SELECT business_id FROM idempotency_record WHERE farm_id=? AND user_id=? AND idempotency_key=? AND request_path=? AND expires_at>NOW()",Long.class,farm,user,key,path);}catch(EmptyResultDataAccessException e){return null;}}
 private long parse(String v,String label){try{return Long.parseLong(v);}catch(NumberFormatException e){throw new DataConflictException(label+"编号格式错误");}}private record PlanState(String item,String status){}
}
