package com.cattlefarm.admin.task;
import cn.dev33.satoken.stp.StpUtil;import com.baomidou.mybatisplus.core.toolkit.IdWorker;import com.cattlefarm.admin.auth.service.AuthService;import com.cattlefarm.admin.common.DataConflictException;import com.cattlefarm.admin.scope.DataScopeService;import org.springframework.dao.EmptyResultDataAccessException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.util.StringUtils;
import java.time.*;import java.util.*;
@Service
public class TaskService{
 private static final Set<String> BUSINESS_TASKS=Set.of("PREGNANCY_CHECK","PREGNANCY_RECHECK","CALVING_CHECK","CALVING_HANDLE","HEALTH_FOLLOW_UP","VACCINATION_EXECUTION","WEIGHT_RECORD","TRANSFER","MIXING_EXECUTION");
 private final JdbcTemplate jdbc;private final AuthService auth;private final DataScopeService scope;public TaskService(JdbcTemplate jdbc,AuthService auth,DataScopeService scope){this.jdbc=jdbc;this.auth=auth;this.scope=scope;}
 public List<TaskDtos.Item>list(String status){long farm=auth.currentFarmId();jdbc.update("UPDATE task SET status='OVERDUE',version=version+1 WHERE farm_id=? AND status IN('PENDING','IN_PROGRESS') AND due_date<CURDATE()",farm);String f=StringUtils.hasText(status)?status:null;return jdbc.query("""
  SELECT t.*,c.ear_tag_no,u.real_name FROM task t LEFT JOIN cattle c ON c.cattle_id=t.related_cattle_id AND c.farm_id=t.farm_id LEFT JOIN sys_user u ON u.user_id=t.assignee_id WHERE t.farm_id=? AND (? IS NULL OR t.status=?) ORDER BY FIELD(t.status,'OVERDUE','PENDING','IN_PROGRESS','DONE','CANCELLED'),t.due_date,t.created_at DESC
  """,(rs,row)->new TaskDtos.Item(Long.toString(rs.getLong("task_id")),rs.getString("source_type"),string(rs.getObject("source_id")),rs.getString("task_type"),rs.getString("title"),string(rs.getObject("related_cattle_id")),rs.getString("ear_tag_no"),rs.getDate("plan_date").toLocalDate(),rs.getDate("due_date").toLocalDate(),rs.getString("priority"),rs.getString("status"),rs.getString("result"),rs.getString("real_name"),rs.getInt("version")),farm,f,f).stream().filter(x->scope.unrestricted()||scope.canAccessTask(Long.parseLong(x.taskId()))).toList();}
 public TaskDtos.Detail detail(long id){long farm=auth.currentFarmId();TaskDtos.Item item=find(id);List<TaskDtos.Target>targets=jdbc.query("""
  SELECT tt.target_type,tt.target_object_id,
   CASE tt.target_type WHEN 'CATTLE' THEN c.ear_tag_no WHEN 'HERD' THEN h.herd_name WHEN 'BARN' THEN b.barn_name ELSE NULL END display_name
  FROM task_target tt
  LEFT JOIN cattle c ON tt.target_type='CATTLE' AND c.farm_id=tt.farm_id AND c.cattle_id=tt.target_object_id
  LEFT JOIN herd h ON tt.target_type='HERD' AND h.farm_id=tt.farm_id AND h.herd_id=tt.target_object_id
  LEFT JOIN barn b ON tt.target_type='BARN' AND b.farm_id=tt.farm_id AND b.barn_id=tt.target_object_id
  WHERE tt.farm_id=? AND tt.task_id=? ORDER BY tt.created_at
  """,(rs,row)->new TaskDtos.Target(rs.getString("target_type"),Long.toString(rs.getLong("target_object_id")),rs.getString("display_name")),farm,id);return new TaskDtos.Detail(item,targets);}
 @Transactional public TaskDtos.Item create(TaskDtos.Create r,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();Long replay=replay(farm,user,key,"/api/v1/tasks");if(replay!=null)return find(replay);if(r.dueDate().isBefore(r.planDate()))throw new DataConflictException("截止日期不能早于计划日期");Long cattle=parseOptional(r.cattleId(),"牛只"),herd=parseOptional(r.herdId(),"牛群"),barn=parseOptional(r.barnId(),"栏舍"),assignee=parseOptional(r.assigneeId(),"负责人");if(assignee==null)assignee=user;validateTargets(farm,cattle,herd,barn);validateAssignee(farm,assignee);long id=IdWorker.getId();idem(farm,user,key,"/api/v1/tasks",id);jdbc.update("INSERT INTO task(task_id,farm_id,source_type,task_type,title,related_cattle_id,related_herd_id,related_barn_id,plan_date,due_date,assignee_id,priority,status,created_by,updated_by) VALUES (?,?,'MANUAL',?,?,?,?,?,?,?,?,?,'PENDING',?,?)",id,farm,r.taskType(),r.title().trim(),cattle,herd,barn,r.planDate(),r.dueDate(),assignee,r.priority()==null?"NORMAL":r.priority(),user,user);addTargets(farm,id,cattle,herd,barn);audit(farm,user,"TASK_CREATED",id,"创建手工任务");return find(id);}
 @Transactional public TaskDtos.Item complete(long id,TaskDtos.Complete r,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();Long replay=replay(farm,user,key,"/api/v1/tasks/"+id+"/complete");if(replay!=null)return find(replay);TaskDtos.Item before=find(id);if(BUSINESS_TASKS.contains(before.taskType()))throw new DataConflictException("该任务必须通过对应业务登记完成，不能直接标记完成");if(List.of("DONE","CANCELLED").contains(before.status()))throw new DataConflictException("任务已结束");idem(farm,user,key,"/api/v1/tasks/"+id+"/complete",id);int n=jdbc.update("UPDATE task SET status='DONE',result=?,completed_by=?,completed_at=NOW(),updated_by=?,version=version+1 WHERE task_id=? AND farm_id=? AND version=?",r.result().trim(),user,user,id,farm,r.version());if(n==0)throw new DataConflictException("任务已被其他人修改，请刷新后重试");audit(farm,user,"TASK_COMPLETED",id,r.result());return find(id);}
 @Transactional public TaskDtos.Item reschedule(long id,TaskDtos.Reschedule r,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();Long replay=replay(farm,user,key,"/api/v1/tasks/"+id+"/reschedule");if(replay!=null)return find(replay);TaskDtos.Item before=find(id);if(List.of("DONE","CANCELLED").contains(before.status()))throw new DataConflictException("已结束任务不可改期");if(r.dueDate().isBefore(r.planDate()))throw new DataConflictException("截止日期不能早于计划日期");idem(farm,user,key,"/api/v1/tasks/"+id+"/reschedule",id);int n=jdbc.update("UPDATE task SET plan_date=?,due_date=?,status='PENDING',updated_by=?,version=version+1 WHERE task_id=? AND farm_id=? AND version=?",r.planDate(),r.dueDate(),user,id,farm,r.version());if(n==0)throw new DataConflictException("任务已被其他人修改，请刷新后重试");audit(farm,user,"TASK_RESCHEDULED",id,r.reason());return find(id);}
 @Transactional public TaskDtos.Item cancel(long id,TaskDtos.Cancel r,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();Long replay=replay(farm,user,key,"/api/v1/tasks/"+id+"/cancel");if(replay!=null)return find(replay);TaskDtos.Item before=find(id);if(List.of("DONE","CANCELLED").contains(before.status()))throw new DataConflictException("任务已结束");idem(farm,user,key,"/api/v1/tasks/"+id+"/cancel",id);int n=jdbc.update("UPDATE task SET status='CANCELLED',cancel_reason=?,cancelled_by=?,cancelled_at=NOW(),updated_by=?,version=version+1 WHERE task_id=? AND farm_id=? AND version=?",r.reason().trim(),user,user,id,farm,r.version());if(n==0)throw new DataConflictException("任务已被其他人修改，请刷新后重试");audit(farm,user,"TASK_CANCELLED",id,r.reason());return find(id);}
 @Transactional public void createAutomatic(long farm,long sourceId,String sourceType,String taskType,String title,Long cattle,Long herd,Long barn,LocalDate plan,LocalDate due,long assignee,String priority){Integer count=jdbc.queryForObject("SELECT COUNT(*) FROM task WHERE farm_id=? AND source_type=? AND source_id=? AND task_type=?",Integer.class,farm,sourceType,sourceId,taskType);if(count!=null&&count>0)return;long id=IdWorker.getId();jdbc.update("INSERT INTO task(task_id,farm_id,source_type,source_id,task_type,title,related_cattle_id,related_herd_id,related_barn_id,plan_date,due_date,assignee_id,priority,status,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,'PENDING',?,?)",id,farm,sourceType,sourceId,taskType,title,cattle,herd,barn,plan,due,assignee,priority,assignee,assignee);addTargets(farm,id,cattle,herd,barn);}
 @Transactional public void finishSource(long farm,String sourceType,long sourceId,String taskType,String result,long user,String status){jdbc.update("UPDATE task SET status=?,result=?,completed_by=?,completed_at=IF(?='DONE',NOW(),completed_at),updated_by=?,version=version+1 WHERE farm_id=? AND source_type=? AND source_id=? AND task_type=? AND status IN('PENDING','IN_PROGRESS','OVERDUE')",status,result,user,status,user,farm,sourceType,sourceId,taskType);}
 @Transactional public void finishOpenForCattle(long farm,String taskType,long cattle,String result,long user){jdbc.update("UPDATE task SET status='DONE',result=?,completed_by=?,completed_at=NOW(),updated_by=?,version=version+1 WHERE farm_id=? AND task_type=? AND related_cattle_id=? AND status IN('PENDING','IN_PROGRESS','OVERDUE')",result,user,user,farm,taskType,cattle);}
 private void validateAssignee(long farm,long user){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM sys_user u JOIN farm_user fu ON fu.user_id=u.user_id AND fu.farm_id=u.farm_id WHERE u.farm_id=? AND u.user_id=? AND u.status='ENABLED' AND fu.status='ENABLED'",Integer.class,farm,user);if(n==null||n==0)throw new DataConflictException("负责人不是当前牛场的启用成员");}private TaskDtos.Item find(long id){if(!scope.unrestricted())scope.assertTask(id);return list(null).stream().filter(x->x.taskId().equals(Long.toString(id))).findFirst().orElseThrow(()->new DataConflictException("任务不存在"));}private void validateTargets(long farm,Long cattle,Long herd,Long barn){if(cattle!=null&&count("cattle","cattle_id",farm,cattle)==0)throw new DataConflictException("关联牛只不存在");if(herd!=null&&count("herd","herd_id",farm,herd)==0)throw new DataConflictException("关联牛群不存在");if(barn!=null&&count("barn","barn_id",farm,barn)==0)throw new DataConflictException("关联栏舍不存在");}private int count(String table,String pk,long farm,long id){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM "+table+" WHERE farm_id=? AND "+pk+"=?",Integer.class,farm,id);return n==null?0:n;}private void addTargets(long farm,long task,Long cattle,Long herd,Long barn){if(cattle!=null)jdbc.update("INSERT INTO task_target(target_id,farm_id,task_id,target_type,target_object_id) VALUES (?, ?,?,'CATTLE',?)",IdWorker.getId(),farm,task,cattle);if(herd!=null)jdbc.update("INSERT INTO task_target(target_id,farm_id,task_id,target_type,target_object_id) VALUES (?, ?,?,'HERD',?)",IdWorker.getId(),farm,task,herd);if(barn!=null)jdbc.update("INSERT INTO task_target(target_id,farm_id,task_id,target_type,target_object_id) VALUES (?, ?,?,'BARN',?)",IdWorker.getId(),farm,task,barn);}
 private void audit(long farm,long user,String action,long id,String reason){jdbc.update("INSERT INTO operation_log(operation_log_id,farm_id,user_id,module_code,action_type,business_type,business_id,reason) VALUES (?,?,?,'TASK',?,'TASK',?,?)",IdWorker.getId(),farm,user,action,id,reason);}private void idem(long farm,long user,String key,String path,long id){jdbc.update("INSERT INTO idempotency_record(farm_id,user_id,idempotency_key,request_path,business_id,expires_at) VALUES (?,?,?,?,?,?)",farm,user,key,path,id,LocalDateTime.now().plusDays(1));}private Long replay(long farm,long user,String key,String path){try{return jdbc.queryForObject("SELECT business_id FROM idempotency_record WHERE farm_id=? AND user_id=? AND idempotency_key=? AND request_path=? AND expires_at>NOW()",Long.class,farm,user,key,path);}catch(EmptyResultDataAccessException e){return null;}}private Long parseOptional(String v,String label){if(!StringUtils.hasText(v))return null;try{return Long.valueOf(v);}catch(NumberFormatException e){throw new DataConflictException(label+"编号格式错误");}}private static String string(Object v){return v==null?null:v.toString();}
}
