package com.cattlefarm.admin.feeding;
import cn.dev33.satoken.annotation.*;import com.cattlefarm.common.api.ApiResponse;import jakarta.validation.Valid;import jakarta.validation.constraints.NotBlank;import org.springframework.http.MediaType;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.util.List;
@RestController @RequestMapping("/api/v1/feeding")
public class FeedingController{
 private final FeedingService service;private final FeedingEnhancementService enhancements;private final RationFormulaImportService importer;public FeedingController(FeedingService service,FeedingEnhancementService enhancements,RationFormulaImportService importer){this.service=service;this.enhancements=enhancements;this.importer=importer;}
 @GetMapping("/ingredients")@SaCheckRole(value={"ADMIN","FARM_MANAGER","VET","BREEDER"},mode=SaMode.OR)public ApiResponse<List<FeedingDtos.Ingredient>>ingredients(){return ApiResponse.success(service.ingredients());}
 @PostMapping("/ingredients")@SaCheckRole(value={"ADMIN","FARM_MANAGER"},mode=SaMode.OR)public ApiResponse<FeedingDtos.Ingredient>createIngredient(@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid@RequestBody FeedingDtos.CreateIngredient r){return ApiResponse.success(service.createIngredient(r,key));}
 @PutMapping("/ingredients/{id}")@SaCheckRole(value={"ADMIN","FARM_MANAGER"},mode=SaMode.OR)public ApiResponse<FeedingDtos.Ingredient>updateIngredient(@PathVariable("id")long id,@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid@RequestBody FeedingDtos.UpdateIngredient r){return ApiResponse.success(enhancements.updateIngredient(id,r,key));}
 @GetMapping("/ration-formulas")public ApiResponse<List<FeedingDtos.Formula>>formulas(){return ApiResponse.success(service.formulas());}
 @PostMapping("/ration-formulas")@SaCheckRole(value={"ADMIN","FARM_MANAGER"},mode=SaMode.OR)public ApiResponse<FeedingDtos.Formula>createFormula(@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid@RequestBody FeedingDtos.CreateFormula r){return ApiResponse.success(service.createFormula(r,key));}
 @PostMapping(value="/ration-formulas/import",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)@SaCheckRole(value={"ADMIN","FARM_MANAGER"},mode=SaMode.OR)public ApiResponse<FeedingDtos.Formula>importFormula(@RequestHeader("X-Idempotency-Key")@NotBlank String key,@RequestParam(required=false)String formulaName,@RequestParam(defaultValue="CUSTOM")String targetType,@RequestParam(required=false)String targetObjectId,@RequestParam(required=false)String remark,@RequestPart MultipartFile file){return ApiResponse.success(importer.importFormula(file,formulaName,targetType,targetObjectId,remark,key));}
 @PutMapping("/ration-formulas/{id}")@SaCheckRole(value={"ADMIN","FARM_MANAGER"},mode=SaMode.OR)public ApiResponse<FeedingDtos.Formula>updateFormula(@PathVariable("id")long id,@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid@RequestBody FeedingDtos.UpdateFormula r){return ApiResponse.success(enhancements.updateFormula(id,r,key));}
 @PostMapping("/ration-formulas/{id}/activate")@SaCheckRole(value={"ADMIN","FARM_MANAGER"},mode=SaMode.OR)public ApiResponse<FeedingDtos.Formula>activate(@PathVariable("id")long id,@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid@RequestBody FeedingDtos.Action r){return ApiResponse.success(service.activate(id,r,key));}
 @GetMapping("/mixing-orders")public ApiResponse<List<FeedingDtos.Order>>orders(){return ApiResponse.success(service.orders());}
 @PostMapping("/mixing-orders")@SaCheckRole(value={"ADMIN","FARM_MANAGER","WORKER"},mode=SaMode.OR)public ApiResponse<FeedingDtos.Order>createOrder(@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid@RequestBody FeedingDtos.CreateOrder r){return ApiResponse.success(service.createOrder(r,key));}
 @PostMapping("/mixing-orders/calculate")@SaCheckRole(value={"ADMIN","FARM_MANAGER"},mode=SaMode.OR)public ApiResponse<FeedingDtos.Order>calculate(@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid@RequestBody FeedingDtos.CreateOrder r){return ApiResponse.success(enhancements.calculate(r,key));}
 @GetMapping("/mixing-orders/{id}")public ApiResponse<FeedingDtos.Order>orderDetail(@PathVariable("id")long id){return ApiResponse.success(enhancements.detail(id));}
 @PostMapping("/mixing-orders/{id}/confirm")@SaCheckRole(value={"ADMIN","FARM_MANAGER"},mode=SaMode.OR)public ApiResponse<FeedingDtos.Order>confirm(@PathVariable("id")long id,@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid@RequestBody FeedingDtos.Action r){return ApiResponse.success(service.confirm(id,r,key));}
 @PostMapping("/mixing-orders/{id}/execute")@SaCheckRole(value={"ADMIN","FARM_MANAGER","WORKER"},mode=SaMode.OR)public ApiResponse<FeedingDtos.Order>execute(@PathVariable("id")long id,@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid@RequestBody FeedingDtos.Execute r){enhancements.assertCanExecute(id);return ApiResponse.success(service.execute(id,r,key));}
 @GetMapping("/mixing-executions")public ApiResponse<List<FeedingDtos.ExecutionItem>>executions(){return ApiResponse.success(enhancements.executions());}
 @PostMapping("/mixing-orders/{id}/cancel")@SaCheckRole(value={"ADMIN","FARM_MANAGER"},mode=SaMode.OR)public ApiResponse<FeedingDtos.Order>cancel(@PathVariable("id")long id,@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid@RequestBody FeedingDtos.Action r){return ApiResponse.success(enhancements.cancel(id,r,key));}
}
