package com.cattlefarm.admin.feeding;

import cn.dev33.satoken.stp.StpUtil;
import com.baomidou.mybatisplus.core.toolkit.IdWorker;
import com.cattlefarm.admin.auth.service.AuthService;
import com.cattlefarm.admin.common.*;
import com.cattlefarm.admin.scope.DataScopeService;
import org.springframework.dao.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.*;

@Service
public class FeedingEnhancementService {
    private final JdbcTemplate jdbc; private final AuthService auth; private final FeedingService core;private final DataScopeService scope;
    public FeedingEnhancementService(JdbcTemplate jdbc,AuthService auth,FeedingService core,DataScopeService scope){this.jdbc=jdbc;this.auth=auth;this.core=core;this.scope=scope;}

    @Transactional public FeedingDtos.Ingredient updateIngredient(long id,FeedingDtos.UpdateIngredient r,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();String path="/api/v1/feeding/ingredients/"+id;Long old=replay(farm,user,key,path);if(old!=null)return core.ingredientDetail(old);core.ingredientDetail(id);if("DISABLED".equals(r.status())&&count("SELECT COUNT(*) FROM ration_formula_item x JOIN ration_formula f ON f.formula_id=x.formula_id AND f.farm_id=x.farm_id WHERE x.farm_id=? AND x.ingredient_id=? AND f.status='ACTIVE'",farm,id)>0)throw new DataConflictException("原料正被启用配方使用，不能停用");idem(farm,user,key,path,id);try{int n=jdbc.update("UPDATE feed_ingredient SET ingredient_name=?,ingredient_type=?,dry_matter_pct=?,tdn_pct=?,metabolizable_energy_value=?,crude_protein_pct=?,starch_pct=?,energy_value=?,gain_energy_value=?,ndf_pct=?,pe_ndf_pct=?,adf_pct=?,ash_pct=?,crude_fat_pct=?,calcium_pct=?,phosphorus_pct=?,rdp_pct=?,unit_price=?,status=?,remark=?,updated_by=?,version=version+1 WHERE farm_id=? AND ingredient_id=? AND version=?",r.ingredientName().trim(),r.ingredientType(),r.dryMatterPct(),r.tdnPct(),r.metabolizableEnergyValue(),r.crudeProteinPct(),r.starchPct(),r.energyValue(),r.gainEnergyValue(),r.ndfPct(),r.peNdfPct(),r.adfPct(),r.ashPct(),r.crudeFatPct(),r.calciumPct(),r.phosphorusPct(),r.rdpPct(),r.unitPrice(),r.status(),r.remark(),user,farm,id,r.version());if(n==0)throw new DataConflictException("原料已被其他人修改，请刷新后重试");}catch(DuplicateKeyException e){throw new DataConflictException("同一牛场内原料名称不能重复");}audit(farm,user,"INGREDIENT_UPDATED","FEED_INGREDIENT",id,"更新原料");return core.ingredientDetail(id);}

    @Transactional public FeedingDtos.Formula updateFormula(long id,FeedingDtos.UpdateFormula r,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();String path="/api/v1/feeding/ration-formulas/"+id;Long old=replay(farm,user,key,path);if(old!=null)return core.formulaDetail(old);FeedingDtos.Formula before=core.formulaDetail(id);if(!"DRAFT".equals(before.status()))throw new DataConflictException("只有草稿配方可以直接修改，已发布配方需创建新版本");validateItems(r.items(),r.dailyIntakeKg());idem(farm,user,key,path,id);try{int n=jdbc.update("UPDATE ration_formula SET formula_name=?,target_type=?,target_object_id=?,daily_intake_kg=?,remark=?,updated_by=?,version=version+1 WHERE farm_id=? AND formula_id=? AND version=? AND status='DRAFT'",r.formulaName().trim(),r.targetType(),optional(r.targetObjectId()),r.dailyIntakeKg(),r.remark(),user,farm,id,r.version());if(n==0)throw new DataConflictException("配方已被其他人修改，请刷新后重试");jdbc.update("DELETE FROM ration_formula_item WHERE farm_id=? AND formula_id=?",farm,id);int sort=0;for(var item:r.items())jdbc.update("INSERT INTO ration_formula_item(item_id,farm_id,formula_id,ingredient_id,ratio_pct,daily_amount_kg,sort_no) VALUES(?,?,?,?,?,?,?)",IdWorker.getId(),farm,id,Long.parseLong(item.ingredientId()),item.ratioPct(),item.dailyAmountKg(),sort++);}catch(DuplicateKeyException e){throw new DataConflictException("配方名称版本或原料明细重复");}audit(farm,user,"FORMULA_UPDATED","RATION_FORMULA",id,"更新草稿配方");return core.formulaDetail(id);}

    public FeedingDtos.Order detail(long id){return core.orderDetail(id);}
    public FeedingDtos.Order calculate(FeedingDtos.CreateOrder r,String key){return core.createOrder(r,key,"/api/v1/feeding/mixing-orders/calculate");}
    public List<FeedingDtos.ExecutionItem> executions(){long farm=auth.currentFarmId();return jdbc.query("SELECT e.*,u.real_name FROM mixing_execution e LEFT JOIN sys_user u ON u.user_id=e.executor_id WHERE e.farm_id=? ORDER BY e.execution_time DESC,e.created_at DESC",(r,n)->new FeedingDtos.ExecutionItem(Long.toString(r.getLong("execution_id")),Long.toString(r.getLong("mixing_order_id")),r.getTimestamp("execution_time").toLocalDateTime(),Long.toString(r.getLong("executor_id")),r.getString("real_name"),r.getString("actual_summary"),r.getString("deviation_note")),farm).stream().filter(x->scope.unrestricted()||scope.canAccessMixingOrder(Long.parseLong(x.orderId()))).toList();}

    public void assertCanExecute(long id){scope.assertMixingOrder(id);long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();Long assignee;try{assignee=jdbc.queryForObject("SELECT assignee_id FROM mixing_order WHERE farm_id=? AND mixing_order_id=?",Long.class,farm,id);}catch(EmptyResultDataAccessException e){throw new DataConflictException("配料单不存在");}if(assignee!=null&&assignee!=user&&!StpUtil.hasRole("ADMIN")&&!StpUtil.hasRole("FARM_MANAGER"))throw new DataScopeForbiddenException("只能执行分配给本人的配料单");}

    @Transactional public FeedingDtos.Order cancel(long id,FeedingDtos.Action r,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();String path="/api/v1/feeding/mixing-orders/"+id+"/cancel";Long old=replay(farm,user,key,path);if(old!=null)return core.orderDetail(old);FeedingDtos.Order order=core.orderDetail(id);if("CANCELLED".equals(order.status()))return order;if("EXECUTED".equals(order.status()))throw new DataConflictException("已执行配料单不能取消");idem(farm,user,key,path,id);int n=jdbc.update("UPDATE mixing_order SET status='CANCELLED',confirm_reason=?,updated_by=?,version=version+1 WHERE farm_id=? AND mixing_order_id=? AND version=? AND status IN('PENDING_CONFIRM','CONFIRMED')",r.reason().trim(),user,farm,id,r.version());if(n==0)throw new DataConflictException("配料单已被其他人修改，请刷新后重试");jdbc.update("UPDATE task SET status='CANCELLED',cancel_reason=?,cancelled_by=?,cancelled_at=NOW(),updated_by=?,version=version+1 WHERE farm_id=? AND source_type='MIXING_ORDER' AND source_id=? AND status IN('PENDING','IN_PROGRESS','OVERDUE')",r.reason().trim(),user,user,farm,id);audit(farm,user,"MIXING_ORDER_CANCELLED","MIXING_ORDER",id,r.reason());return core.orderDetail(id);}
    @Transactional public boolean deleteOrder(long id,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();String path="/api/v1/feeding/mixing-orders/"+id;Long old=replay(farm,user,key,path);if(old!=null)return true;FeedingDtos.Order order=core.orderDetail(id);long executions=count("SELECT COUNT(*) FROM mixing_execution WHERE farm_id=? AND mixing_order_id=?",farm,id);if(executions>0||"EXECUTED".equals(order.status()))throw new DataConflictException("该配料单已有执行记录，请先删除执行记录");if("CONFIRMED".equals(order.status()))throw new DataConflictException("已确认配料单请先取消后再删除");if(!List.of("PENDING_CONFIRM","CANCELLED").contains(order.status()))throw new DataConflictException("当前状态的配料单不能删除");idem(farm,user,key,path,id);jdbc.update("DELETE FROM task_target WHERE farm_id=? AND task_id IN(SELECT task_id FROM task WHERE farm_id=? AND source_type='MIXING_ORDER' AND source_id=?)",farm,farm,id);jdbc.update("DELETE FROM task WHERE farm_id=? AND source_type='MIXING_ORDER' AND source_id=?",farm,id);jdbc.update("DELETE FROM mixing_order_item WHERE farm_id=? AND mixing_order_id=?",farm,id);int deleted=jdbc.update("DELETE FROM mixing_order WHERE farm_id=? AND mixing_order_id=? AND version=? AND status IN('PENDING_CONFIRM','CANCELLED')",farm,id,order.version());if(deleted==0)throw new DataConflictException("配料单已被其他人修改，请刷新后重试");audit(farm,user,"MIXING_ORDER_DELETED","MIXING_ORDER",id,"删除配料单");return true;}
    @Transactional public boolean deleteExecution(long id,String key){long farm=auth.currentFarmId(),user=StpUtil.getLoginIdAsLong();String path="/api/v1/feeding/mixing-executions/"+id;Long old=replay(farm,user,key,path);if(old!=null)return true;Long orderId;try{orderId=jdbc.queryForObject("SELECT mixing_order_id FROM mixing_execution WHERE farm_id=? AND execution_id=?",Long.class,farm,id);}catch(EmptyResultDataAccessException e){throw new DataConflictException("执行记录不存在");}scope.assertMixingOrder(orderId);FeedingDtos.Order order=core.orderDetail(orderId);if(!"EXECUTED".equals(order.status()))throw new DataConflictException("配料单状态与执行记录不一致，请刷新后重试");idem(farm,user,key,path,id);int deleted=jdbc.update("DELETE FROM mixing_execution WHERE farm_id=? AND execution_id=? AND mixing_order_id=?",farm,id,orderId);if(deleted==0)throw new DataConflictException("执行记录已被其他人删除，请刷新后重试");int restored=jdbc.update("UPDATE mixing_order SET status='CONFIRMED',updated_by=?,version=version+1 WHERE farm_id=? AND mixing_order_id=? AND version=? AND status='EXECUTED'",user,farm,orderId,order.version());if(restored==0)throw new DataConflictException("配料单已被其他人修改，请刷新后重试");jdbc.update("UPDATE task SET status=IF(due_date<CURDATE(),'OVERDUE','PENDING'),result=NULL,completed_by=NULL,completed_at=NULL,cancel_reason=NULL,cancelled_by=NULL,cancelled_at=NULL,updated_by=?,version=version+1 WHERE farm_id=? AND source_type='MIXING_ORDER' AND source_id=? AND task_type='MIXING_EXECUTION' AND status='DONE'",user,farm,orderId);audit(farm,user,"MIXING_EXECUTION_DELETED","MIXING_EXECUTION",id,"删除执行记录并将配料单回退为已确认");return true;}

    private void validateItems(List<FeedingDtos.FormulaItem>items,BigDecimal intake){long farm=auth.currentFarmId();Set<String>ids=new HashSet<>();BigDecimal sum=BigDecimal.ZERO;for(var item:items){if(!ids.add(item.ingredientId()))throw new DataConflictException("配方中不能重复选择同一种原料");core.ingredientDetail(Long.parseLong(item.ingredientId()));sum=sum.add(item.dailyAmountKg());}if(sum.subtract(intake).abs().compareTo(new BigDecimal("0.01"))>0)throw new DataConflictException("各原料日用量合计必须等于日采食量");}
    private Long optional(String value){if(value==null||value.isBlank())return null;try{return Long.valueOf(value);}catch(Exception e){throw new DataConflictException("目标对象编号格式错误");}}private long count(String sql,Object...args){Number n=jdbc.queryForObject(sql,Number.class,args);return n==null?0:n.longValue();}private void audit(long f,long u,String a,String t,long id,String reason){jdbc.update("INSERT INTO operation_log(operation_log_id,farm_id,user_id,module_code,action_type,business_type,business_id,reason) VALUES(?,?,?,'FEEDING',?,?,?,?)",IdWorker.getId(),f,u,a,t,id,reason);}private void idem(long f,long u,String k,String p,long id){jdbc.update("INSERT INTO idempotency_record(farm_id,user_id,idempotency_key,request_path,business_id,expires_at) VALUES(?,?,?,?,?,?)",f,u,k,p,id,LocalDateTime.now().plusDays(1));}private Long replay(long f,long u,String k,String p){try{return jdbc.queryForObject("SELECT business_id FROM idempotency_record WHERE farm_id=? AND user_id=? AND idempotency_key=? AND request_path=? AND expires_at>NOW()",Long.class,f,u,k,p);}catch(EmptyResultDataAccessException e){return null;}}
}
