package com.cattlefarm.admin.breeding;
import cn.dev33.satoken.annotation.*;import com.cattlefarm.common.api.ApiResponse;import com.cattlefarm.admin.correction.*;import jakarta.validation.Valid;import jakarta.validation.constraints.NotBlank;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController @RequestMapping("/api/v1/breeding")
public class BreedingController{private final BreedingService service;private final BusinessCorrectionService corrections;public BreedingController(BreedingService service,BusinessCorrectionService corrections){this.service=service;this.corrections=corrections;}
 @GetMapping("/events")public ApiResponse<List<BreedingDtos.EventItem>>events(@RequestParam(name="cattleId",required=false)String id){return ApiResponse.success(service.events(id));}
 @GetMapping("/heats")public ApiResponse<List<BreedingDtos.HeatItem>>heats(@RequestParam(name="cattleId",required=false)String id){return ApiResponse.success(service.heats(id));}
 @GetMapping("/inseminations")public ApiResponse<List<BreedingDtos.InseminationItem>>inseminations(@RequestParam(name="cattleId",required=false)String id){return ApiResponse.success(service.inseminations(id));}
 @GetMapping("/pregnancy-checks")public ApiResponse<List<BreedingDtos.PregnancyItem>>pregnancyChecks(@RequestParam(name="cattleId",required=false)String id){return ApiResponse.success(service.pregnancyChecks(id));}
 @GetMapping("/calvings")public ApiResponse<List<BreedingDtos.CalvingItem>>calvings(@RequestParam(name="cattleId",required=false)String id){return ApiResponse.success(service.calvings(id));}
 @GetMapping("/due-cows")public ApiResponse<List<BreedingDtos.DueCow>>dueCows(@RequestParam(name="days",defaultValue="30")int days){return ApiResponse.success(service.dueCows(days));}
 @PostMapping({"/estrus","/heats"})@SaCheckRole(value={"ADMIN","FARM_MANAGER","BREEDER"},mode=SaMode.OR)public ApiResponse<BreedingDtos.Result>estrus(@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid @RequestBody BreedingDtos.Estrus r){return ApiResponse.success(service.estrus(r,key));}
 @PostMapping("/inseminations")@SaCheckRole(value={"ADMIN","FARM_MANAGER","BREEDER"},mode=SaMode.OR)public ApiResponse<BreedingDtos.Result>breed(@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid @RequestBody BreedingDtos.Breed r){return ApiResponse.success(service.breed(r,key));}
 @PostMapping("/pregnancy-checks")@SaCheckRole(value={"ADMIN","FARM_MANAGER","BREEDER"},mode=SaMode.OR)public ApiResponse<BreedingDtos.Result>pregnancy(@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid @RequestBody BreedingDtos.Pregnancy r){return ApiResponse.success(service.pregnancy(r,key));}
 @PostMapping("/calvings")@SaCheckRole(value={"ADMIN","FARM_MANAGER","BREEDER"},mode=SaMode.OR)public ApiResponse<BreedingDtos.Result>calving(@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid @RequestBody BreedingDtos.Calving r){return ApiResponse.success(service.calving(r,key));}
 @PostMapping("/heats/{id}/void")@SaCheckRole(value={"ADMIN","FARM_MANAGER","BREEDER"},mode=SaMode.OR)public ApiResponse<CorrectionResult>voidHeat(@PathVariable long id,@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid@RequestBody VoidBusinessRequest r){return ApiResponse.success(corrections.voidBreeding("HEAT",id,r,key));}
 @PostMapping("/inseminations/{id}/void")@SaCheckRole(value={"ADMIN","FARM_MANAGER","BREEDER"},mode=SaMode.OR)public ApiResponse<CorrectionResult>voidInsemination(@PathVariable long id,@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid@RequestBody VoidBusinessRequest r){return ApiResponse.success(corrections.voidBreeding("INSEMINATION",id,r,key));}
 @PostMapping("/pregnancy-checks/{id}/void")@SaCheckRole(value={"ADMIN","FARM_MANAGER","BREEDER"},mode=SaMode.OR)public ApiResponse<CorrectionResult>voidPregnancy(@PathVariable long id,@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid@RequestBody VoidBusinessRequest r){return ApiResponse.success(corrections.voidBreeding("PREGNANCY_CHECK",id,r,key));}
 @PostMapping("/calvings/{id}/void")@SaCheckRole(value={"ADMIN","FARM_MANAGER"},mode=SaMode.OR)public ApiResponse<CorrectionResult>voidCalving(@PathVariable long id,@RequestHeader("X-Idempotency-Key")@NotBlank String key,@Valid@RequestBody VoidBusinessRequest r){return ApiResponse.success(corrections.voidBreeding("CALVING",id,r,key));}
}
